const translations: Record<string, Record<string, string>> = {
  en: { title: "All appointments", createAppointment: "Create appointment", availabilityRequests: "Availability requests", availabilityDescription: "No patient data is included in these requests.", markResolved: "Mark resolved", processing: "Processing…", allSpecialists: "All specialists", allClinics: "All clinics", allStatuses: "All statuses", patient: "Patient", specialist: "Specialist", specialties: "Specialties", clinic: "Clinic", date: "Date", time: "Time", status: "Status", actions: "Actions", scheduled: "Scheduled", awaitingConfirmation: "Awaiting confirmation", completed: "Completed", noShow: "Patient absent", cancelled: "Cancelled", rescheduled: "Rescheduled", markCompleted: "Complete", cancelPatient: "Cancelled by patient", cancelClinicEmergency: "Clinical emergency", reschedule: "Reschedule", modifySchedule: "Modify time and clinic" },
  es: { title: "Todas las citas", createAppointment: "Crear una cita", availabilityRequests: "Solicitudes de disponibilidad", availabilityDescription: "No se incluyen datos del paciente en estas solicitudes.", markResolved: "Marcar como resuelta", processing: "Procesando…", allSpecialists: "Todos los especialistas", allClinics: "Todas las clínicas", allStatuses: "Todos los estados", patient: "Paciente", specialist: "Especialista", specialties: "Especialidades", clinic: "Clínica", date: "Fecha", time: "Hora", status: "Estado", actions: "Acciones", scheduled: "Programada", awaitingConfirmation: "Pendiente de confirmación", completed: "Completada", noShow: "Paciente ausente", cancelled: "Cancelada", rescheduled: "Reprogramada", markCompleted: "Completar", cancelPatient: "Cancelada por el paciente", cancelClinicEmergency: "Urgencia clínica", reschedule: "Reprogramar", modifySchedule: "Modificar la hora y la clínica" },
  vi: { title: "Tất cả lịch hẹn", createAppointment: "Tạo lịch hẹn", availabilityRequests: "Yêu cầu về lịch trống", availabilityDescription: "Không có dữ liệu bệnh nhân trong các yêu cầu này.", markResolved: "Đánh dấu đã xử lý", processing: "Đang xử lý…", allSpecialists: "Tất cả chuyên gia", allClinics: "Tất cả phòng khám", allStatuses: "Tất cả trạng thái", patient: "Bệnh nhân", specialist: "Chuyên gia", specialties: "Chuyên khoa", clinic: "Phòng khám", date: "Ngày", time: "Giờ", status: "Trạng thái", actions: "Thao tác", scheduled: "Đã lên lịch", awaitingConfirmation: "Chờ xác nhận", completed: "Đã hoàn tất", noShow: "Bệnh nhân vắng mặt", cancelled: "Đã hủy", rescheduled: "Đã dời lịch", markCompleted: "Hoàn tất", cancelPatient: "Bệnh nhân hủy", cancelClinicEmergency: "Khẩn cấp tại phòng khám", reschedule: "Dời lịch", modifySchedule: "Sửa giờ và phòng khám" },
  no: { title: "Alle timer", createAppointment: "Opprett time", availabilityRequests: "Forespørsler om tilgjengelighet", availabilityDescription: "Ingen pasientdata er inkludert i disse forespørslene.", markResolved: "Merk som behandlet", processing: "Behandler…", allSpecialists: "Alle spesialister", allClinics: "Alle klinikker", allStatuses: "Alle statuser", patient: "Pasient", specialist: "Spesialist", specialties: "Spesialiteter", clinic: "Klinikk", date: "Dato", time: "Tid", status: "Status", actions: "Handlinger", scheduled: "Planlagt", awaitingConfirmation: "Avventer bekreftelse", completed: "Fullført", noShow: "Pasienten møtte ikke", cancelled: "Avlyst", rescheduled: "Flyttet", markCompleted: "Fullfør", cancelPatient: "Avlyst av pasienten", cancelClinicEmergency: "Klinisk nødsituasjon", reschedule: "Flytt", modifySchedule: "Endre tid og klinikk" },
  ja: { title: "すべての予約", createAppointment: "予約を作成", availabilityRequests: "空き状況の依頼", availabilityDescription: "これらの依頼には患者データは含まれていません。", markResolved: "対応済みにする", processing: "処理中…", allSpecialists: "すべての専門医", allClinics: "すべてのクリニック", allStatuses: "すべてのステータス", patient: "患者", specialist: "専門医", specialties: "専門分野", clinic: "クリニック", date: "日付", time: "時間", status: "ステータス", actions: "操作", scheduled: "予定", awaitingConfirmation: "確認待ち", completed: "完了", noShow: "患者欠席", cancelled: "キャンセル", rescheduled: "変更済み", markCompleted: "完了にする", cancelPatient: "患者によるキャンセル", cancelClinicEmergency: "臨床上の緊急事態", reschedule: "変更", modifySchedule: "時間とクリニックを変更" },
  zh: { title: "所有预约", createAppointment: "创建预约", availabilityRequests: "可用性请求", availabilityDescription: "这些请求中不包含患者数据。", markResolved: "标记为已处理", processing: "处理中…", allSpecialists: "所有专科医生", allClinics: "所有诊所", allStatuses: "所有状态", patient: "患者", specialist: "专科医生", specialties: "专科", clinic: "诊所", date: "日期", time: "时间", status: "状态", actions: "操作", scheduled: "已安排", awaitingConfirmation: "待确认", completed: "已完成", noShow: "患者未到", cancelled: "已取消", rescheduled: "已改期", markCompleted: "完成", cancelPatient: "患者取消", cancelClinicEmergency: "临床紧急情况", reschedule: "改期", modifySchedule: "修改时间和诊所" },
  he: { title: "כל התורים", createAppointment: "יצירת תור", availabilityRequests: "בקשות זמינות", availabilityDescription: "לא נכללים נתוני מטופלים בבקשות אלה.", markResolved: "סימון כטופל", processing: "בטיפול…", allSpecialists: "כל המומחים", allClinics: "כל המרפאות", allStatuses: "כל הסטטוסים", patient: "מטופל", specialist: "מומחה", specialties: "תחומי התמחות", clinic: "מרפאה", date: "תאריך", time: "שעה", status: "סטטוס", actions: "פעולות", scheduled: "מתוכנן", awaitingConfirmation: "ממתין לאישור", completed: "הושלם", noShow: "המטופל לא הגיע", cancelled: "בוטל", rescheduled: "נקבע מחדש", markCompleted: "השלמה", cancelPatient: "בוטל על ידי המטופל", cancelClinicEmergency: "מקרה חירום קליני", reschedule: "קביעת מועד חדש", modifySchedule: "שינוי שעה ומרפאה" },
  ko: { title: "모든 예약", createAppointment: "예약 만들기", availabilityRequests: "예약 가능 여부 요청", availabilityDescription: "이 요청에는 환자 데이터가 포함되지 않습니다.", markResolved: "처리 완료로 표시", processing: "처리 중…", allSpecialists: "모든 전문의", allClinics: "모든 진료소", allStatuses: "모든 상태", patient: "환자", specialist: "전문의", specialties: "전문 분야", clinic: "진료소", date: "날짜", time: "시간", status: "상태", actions: "작업", scheduled: "예약됨", awaitingConfirmation: "확인 대기", completed: "완료", noShow: "환자 미방문", cancelled: "취소됨", rescheduled: "일정 변경됨", markCompleted: "완료", cancelPatient: "환자 취소", cancelClinicEmergency: "임상 응급 상황", reschedule: "일정 변경", modifySchedule: "시간 및 진료소 변경" },
};

const pendingRequestTranslations: Record<string, string> = {
  en: "No pending requests.",
  es: "No hay solicitudes pendientes.",
  vi: "Không có yêu cầu nào đang chờ xử lý.",
  no: "Ingen ventende forespørsler.",
  ja: "保留中の依頼はありません。",
  zh: "没有待处理请求。",
  he: "אין בקשות ממתינות.",
  ko: "대기 중인 요청이 없습니다.",
};

export function appointmentListLabel(locale: string, key: string, french: string) {
  const language = locale.toLowerCase().split("-")[0];
  return translations[language]?.[key]
    || (key === "noPendingRequests" ? pendingRequestTranslations[language] : undefined)
    || french;
}
