import { UI_LABELS_FR } from "./uiLabels.fr";
import { baseUiLocale, validUiTranslation } from "./uiLocales";
import { clinicalUiRows } from "./clinicalUiLabels";
import { getClinicalResultStrings } from "./clinicalResultStrings";
import { getClinicalFormReviewedStrings } from "./clinicalFormStrings";
import { getCachedResultNoticeLabels } from "./cachedResultNoticeLabels";
import compiled from "./compiledUiTranslations.json";

const labels = UI_LABELS_FR.clinicalDemo;
const languages = ["fr", "en", "es", "ko", "vi", "no", "ja", "zh", "he"];
function sourceAt(path: string): string {
    let value: unknown = labels;
    for (const key of path.split(".")) value = (value as Record<string, unknown>)[key];
    if (typeof value !== "string") throw new Error(`Invalid clinical demo UI key: ${path}`);
    return value;
}
function row(path: string, ...translations: string[]): readonly string[] {
    return [sourceAt(path), ...translations];
}

// Fixed UI labels only. Never translate clinical response content or patient data.
const explicitRows: readonly (readonly string[])[] = [
row("resultAccordions.referencesHint", "ClinIA does not present these results at random. Use these clinical references to verify the analysis and explore further reading.", "ClinIA no presenta estos resultados al azar. Use estas referencias clínicas para verificar el análisis y profundizar en la lectura.", "ClinIA는 이러한 결과를 무작위로 제시하지 않습니다. 이 임상 참고자료를 사용하여 분석을 검증하고 더 자세히 읽어 보세요.", "ClinIA không đưa ra các kết quả này một cách ngẫu nhiên. Sử dụng các tài liệu tham khảo lâm sàng này để xác minh phân tích và đọc sâu hơn.", "ClinIA presenterer ikke disse resultatene tilfeldig. Bruk de kliniske referansene til å kontrollere analysen og lese videre.", "ClinIAはこれらの結果を無作為に提示しているわけではありません。臨床参考文献を使って分析を検証し、さらに詳しく確認してください。", "ClinIA 并非随机呈现这些结果。请使用这些临床参考资料核查分析并进一步阅读。", "ClinIA אינה מציגה את התוצאות האלה באופן אקראי. יש להשתמש במקורות הקליניים לאימות הניתוח ולקריאה מעמיקה יותר."),
row("cloudContentGuard.neutralizationReview.cancel", "Cancel", "Cancelar", "취소", "Hủy", "Avbryt", "キャンセル", "取消", "ביטול"),
row("loading.openAiRequestInProgress", "Clinical analysis in progress...", "Análisis clínico en curso...", "임상 분석 진행 중...", "Đang phân tích lâm sàng...", "Klinisk analyse pågår...", "臨床分析中...", "正在进行临床分析...", "ניתוח קליני מתבצע..."),
row("cloudContentGuard.title", "Analysis stopped before transmission", "Análisis detenido antes del envío", "전송 전에 분석 중단됨", "Phân tích đã dừng trước khi gửi", "Analysen stoppet før overføring", "送信前に分析を停止しました", "分析在传输前已停止", "הניתוח הופסק לפני השליחה"),
row("cloudContentGuard.description", "Some fields contain free text that cannot be sent to OpenAI. None of these values were sent to the cloud service.", "Algunos campos contienen texto libre que no se puede enviar a OpenAI. Ninguno de estos valores se envió al servicio en la nube.", "일부 필드에 OpenAI로 전송할 수 없는 자유 텍스트가 포함되어 있습니다. 이 값들은 클라우드 서비스로 전송되지 않았습니다.", "Một số trường chứa văn bản tự do không thể gửi đến OpenAI. Không có giá trị nào trong số này được gửi đến dịch vụ đám mây.", "Noen felter inneholder fritekst som ikke kan sendes til OpenAI. Ingen av disse verdiene ble sendt til skytjenesten.", "一部の項目にOpenAIへ送信できない自由記述が含まれています。これらの値はクラウドサービスに送信されていません。", "某些字段包含无法发送给 OpenAI 的自由文本。这些值均未发送到云服务。", "חלק מהשדות מכילים טקסט חופשי שלא ניתן לשלוח ל־OpenAI. אף אחד מהערכים האלה לא נשלח לשירות הענן."),
row("cloudContentGuard.fieldsLabel", "Fields to correct:", "Campos que corregir:", "수정할 필드:", "Các trường cần sửa:", "Felter som må rettes:", "修正が必要な項目：", "需要更正的字段：", "שדות לתיקון:"),
row("cloudContentGuard.fieldLabels.diagnosis", "Diagnosis or main clinical reason", "Diagnóstico o motivo clínico principal", "진단 또는 주요 임상 사유", "Chẩn đoán hoặc lý do lâm sàng chính", "Diagnose eller hovedårsak til klinisk vurdering", "診断または主な臨床的理由", "诊断或主要临床原因", "אבחנה או סיבה קלינית עיקרית"),
row("cloudContentGuard.fieldLabels.symptoms", "Main symptoms", "Síntomas principales", "주요 증상", "Triệu chứng chính", "Hovedsymptomer", "主な症状", "主要症状", "תסמינים עיקריים"),
row("cloudContentGuard.fieldLabels.medical_history", "Medical history", "Antecedentes médicos", "병력", "Tiền sử bệnh", "Sykehistorie", "既往歴", "病史", "היסטוריה רפואית"),
row("cloudContentGuard.fieldLabels.current_medications", "Current medications", "Medicamentos actuales", "현재 복용 약물", "Thuốc hiện tại", "Nåværende legemidler", "現在の薬剤", "当前用药", "תרופות נוכחיות"),
row("cloudContentGuard.fieldLabels.diabetes_context", "Diabetes context", "Contexto de la diabetes", "당뇨병 관련 상황", "Bối cảnh bệnh tiểu đường", "Diabeteskontekst", "糖尿病の背景", "糖尿病背景", "הקשר הסוכרת"),
row("cloudContentGuard.fieldLabels.patient", "Patient clinical parameters", "Parámetros clínicos del paciente", "환자 임상 매개변수", "Thông số lâm sàng của bệnh nhân", "Pasientens kliniske parametere", "患者の臨床パラメータ", "患者临床参数", "הפרמטרים הקליניים של המטופל"),
row("cloudContentGuard.action", "Correct parameters", "Corregir parámetros", "매개변수 수정", "Sửa thông số", "Rett parametere", "パラメータを修正", "更正参数", "תיקון הפרמטרים"),
row("cloudContentGuard.neutralizationReview.title", "Review before transmission", "Revisión antes del envío", "전송 전 확인", "Kiểm tra trước khi gửi", "Kontroll før overføring", "送信前の確認", "传输前检查", "בדיקה לפני שליחה"),
row("cloudContentGuard.neutralizationReview.description", "ClinIA will remove the identified elements before any transmission to OpenAI. Review the corrected values, then confirm to continue.", "ClinIA eliminará los elementos identificados antes de cualquier envío a OpenAI. Revise los valores corregidos y confirme para continuar.", "ClinIA는 OpenAI로 전송하기 전에 식별된 요소를 제거합니다. 수정된 값을 확인한 다음 계속 진행을 승인하세요.", "ClinIA sẽ loại bỏ các yếu tố đã xác định trước khi gửi đến OpenAI. Kiểm tra các giá trị đã sửa rồi xác nhận để tiếp tục.", "ClinIA fjerner de identifiserte elementene før noe sendes til OpenAI. Kontroller de rettede verdiene og bekreft for å fortsette.", "ClinIAはOpenAIへの送信前に、検出された要素を削除します。修正後の値を確認し、続行を承認してください。", "ClinIA 将在向 OpenAI 传输前移除已识别的内容。请检查更正后的值，然后确认继续。", "ClinIA תסיר את הרכיבים שזוהו לפני כל שליחה ל־OpenAI. יש לבדוק את הערכים המתוקנים ואז לאשר את ההמשך."),
row("cloudContentGuard.neutralizationReview.original", "Original value", "Valor original", "원래 값", "Giá trị gốc", "Opprinnelig verdi", "元の値", "原始值", "ערך מקורי"),
row("cloudContentGuard.neutralizationReview.corrected", "Corrected value", "Valor corregido", "수정된 값", "Giá trị đã sửa", "Rettet verdi", "修正後の値", "更正后的值", "ערך מתוקן"),
row("cloudContentGuard.neutralizationReview.empty", "No elements retained", "Ningún elemento conservado", "보존된 요소 없음", "Không giữ lại yếu tố nào", "Ingen elementer beholdt", "保持された要素なし", "未保留任何内容", "לא נשמרו רכיבים"),
row("cloudContentGuard.neutralizationReview.continue", "Continue with corrected parameters", "Continuar con los parámetros corregidos", "수정된 매개변수로 계속", "Tiếp tục với thông số đã sửa", "Fortsett med rettede parametere", "修正後のパラメータで続行", "使用更正后的参数继续", "המשך עם הפרמטרים המתוקנים"),
row("cloudContentGuard.requestBoundary.title", "Analysis not sent", "Análisis no enviado", "분석 전송되지 않음", "Phân tích chưa được gửi", "Analysen ble ikke sendt", "分析は送信されていません", "分析未发送", "הניתוח לא נשלח"),
row("cloudContentGuard.requestBoundary.messages.INVALID_CLINICAL_REQUEST_SHAPE", "The request contains information not recognized by the ClinIA form. It was not sent to the analysis service.", "La solicitud contiene información no reconocida por el formulario de ClinIA. No se envió al servicio de análisis.", "요청에 ClinIA 양식에서 인식하지 못하는 정보가 포함되어 있습니다. 분석 서비스로 전송되지 않았습니다.", "Yêu cầu chứa thông tin mà biểu mẫu ClinIA không nhận dạng được. Yêu cầu chưa được gửi đến dịch vụ phân tích.", "Forespørselen inneholder informasjon som ClinIA-skjemaet ikke gjenkjenner. Den ble ikke sendt til analysetjenesten.", "要求にClinIAのフォームが認識しない情報が含まれています。分析サービスには送信されていません。", "请求包含 ClinIA 表单无法识别的信息，未发送到分析服务。", "הבקשה מכילה מידע שטופס ClinIA אינו מזהה. היא לא נשלחה לשירות הניתוח."),
row("cloudContentGuard.requestBoundary.messages.INVALID_CLINICAL_INPUT_BOUNDARY", "Some clinical parameters exceed the allowed limits. They were not sent to the analysis service.", "Algunos parámetros clínicos superan los límites permitidos. No se enviaron al servicio de análisis.", "일부 임상 매개변수가 허용 범위를 초과합니다. 분석 서비스로 전송되지 않았습니다.", "Một số thông số lâm sàng vượt giới hạn cho phép. Chúng chưa được gửi đến dịch vụ phân tích.", "Noen kliniske parametere overskrider tillatte grenser. De ble ikke sendt til analysetjenesten.", "一部の臨床パラメータが許容範囲を超えています。分析サービスには送信されていません。", "某些临床参数超出允许范围，未发送到分析服务。", "חלק מהפרמטרים הקליניים חורגים מהגבולות המותרים. הם לא נשלחו לשירות הניתוח."),
row("cloudContentGuard.requestBoundary.messages.CLINICAL_REQUEST_TOO_LARGE", "The clinical parameters are too large to analyze in a single request. They were not sent to the analysis service.", "Los parámetros clínicos son demasiado voluminosos para analizarlos en una sola solicitud. No se enviaron al servicio de análisis.", "임상 매개변수가 너무 커서 한 번의 요청으로 분석할 수 없습니다. 분석 서비스로 전송되지 않았습니다.", "Các thông số lâm sàng quá lớn để phân tích trong một yêu cầu. Chúng chưa được gửi đến dịch vụ phân tích.", "De kliniske parameterne er for store til å analyseres i én forespørsel. De ble ikke sendt til analysetjenesten.", "臨床パラメータが大きすぎるため、1回の要求で分析できません。分析サービスには送信されていません。", "临床参数过大，无法在单个请求中分析，未发送到分析服务。", "הפרמטרים הקליניים גדולים מדי לניתוח בבקשה אחת. הם לא נשלחו לשירות הניתוח."),
row("cloudContentGuard.requestBoundary.messages.ANONYMOUS_CLINICAL_DEMO_RATE_LIMITED", "The demo has reached its temporary request limit. No clinical result was saved. Try again shortly.", "La demostración alcanzó su límite temporal de solicitudes. No se guardó ningún resultado clínico. Vuelva a intentarlo en unos instantes.", "데모가 임시 요청 한도에 도달했습니다. 임상 결과는 저장되지 않았습니다. 잠시 후 다시 시도하세요.", "Bản demo đã đạt giới hạn yêu cầu tạm thời. Không có kết quả lâm sàng nào được lưu. Hãy thử lại sau ít phút.", "Demoen har nådd sin midlertidige forespørselsgrense. Ingen kliniske resultater ble lagret. Prøv igjen om litt.", "デモの一時的な要求上限に達しました。臨床結果は保存されていません。しばらくしてから再試行してください。", "演示已达到临时请求上限。未保存任何临床结果。请稍后重试。", "ההדגמה הגיעה למגבלת הבקשות הזמנית. לא נשמרה תוצאה קלינית. יש לנסות שוב בעוד זמן קצר."),
row("form.help.button", "Help with this field", "Ayuda para este campo", "이 필드 도움말", "Trợ giúp cho trường này", "Hjelp med dette feltet", "この項目のヘルプ", "此字段的帮助", "עזרה לשדה זה"),
row("form.help.inputMode", "Choose “Existing patient” to reuse structured parameters already authorized in a record. Choose “Manual entry” to analyze a case without loading a patient record.", "Elija «Paciente existente» para reutilizar los parámetros estructurados ya autorizados en un expediente. Elija «Entrada manual» para analizar un caso sin cargar un expediente de paciente.", "‘기존 환자’를 선택하면 기록에서 이미 승인된 구조화된 매개변수를 재사용합니다. 환자 기록을 불러오지 않고 사례를 분석하려면 ‘수동 입력’을 선택하세요.", "Chọn “Bệnh nhân hiện có” để sử dụng lại các thông số có cấu trúc đã được phép trong hồ sơ. Chọn “Nhập thủ công” để phân tích ca mà không tải hồ sơ bệnh nhân.", "Velg «Eksisterende pasient» for å gjenbruke strukturerte parametere som allerede er godkjent i en journal. Velg «Manuell registrering» for å analysere et tilfelle uten å laste en pasientjournal.", "「既存の患者」を選択すると、記録内で既に許可された構造化パラメータを再利用します。患者記録を読み込まずに症例を分析するには「手動入力」を選択してください。", "选择“现有患者”以复用档案中已获授权的结构化参数。选择“手动输入”可在不加载患者档案的情况下分析病例。", "יש לבחור ״מטופל קיים״ לשימוש חוזר בפרמטרים מובנים שכבר אושרו בתיק. יש לבחור ״הזנה ידנית״ לניתוח מקרה בלי לטעון תיק מטופל."),
row("form.help.patientSearch", "Search only among your own patients. Free-text clinical notes are never added automatically to the analysis request.", "Busque únicamente entre sus propios pacientes. Las notas clínicas de texto libre nunca se añaden automáticamente a la solicitud de análisis.", "본인의 환자만 검색하세요. 자유 형식 임상 노트는 분석 요청에 자동으로 추가되지 않습니다.", "Chỉ tìm trong các bệnh nhân của bạn. Ghi chú lâm sàng tự do không bao giờ được tự động thêm vào yêu cầu phân tích.", "Søk bare blant dine egne pasienter. Kliniske fritekstnotater legges aldri automatisk til analyseforespørselen.", "自分の患者のみを検索してください。自由記述の臨床ノートが分析要求に自動追加されることはありません。", "仅搜索您自己的患者。自由文本临床记录绝不会自动添加到分析请求。", "יש לחפש רק בין המטופלים שלך. הערות קליניות בטקסט חופשי לעולם אינן נוספות אוטומטית לבקשת הניתוח."),
row("form.help.clinicalField", "Choose the clinical field before the example case. This prepares the relevant form options.", "Elija el área clínica antes del caso de ejemplo. Esto prepara las opciones pertinentes del formulario.", "예제 사례 전에 임상 분야를 선택하세요. 양식의 관련 옵션이 준비됩니다.", "Chọn lĩnh vực lâm sàng trước ca ví dụ. Thao tác này chuẩn bị các tùy chọn biểu mẫu phù hợp.", "Velg det kliniske feltet før eksempeltilfellet. Dette klargjør de relevante skjemavalgene.", "症例例の前に臨床分野を選択してください。関連するフォームの選択肢が準備されます。", "在示例病例之前选择临床领域，以准备相关表单选项。", "יש לבחור את התחום הקליני לפני מקרה הדוגמה. כך יוכנו אפשרויות הטופס הרלוונטיות."),
row("form.help.diagnosis", "Enter a confirmed diagnosis or the main clinical reason. Do not add information that could identify the patient.", "Introduzca un diagnóstico confirmado o el motivo clínico principal. No añada información que permita identificar al paciente.", "확인된 진단 또는 주요 임상 사유를 입력하세요. 환자를 식별할 수 있는 정보는 추가하지 마세요.", "Nhập chẩn đoán đã xác nhận hoặc lý do lâm sàng chính. Không thêm thông tin có thể xác định danh tính bệnh nhân.", "Angi en bekreftet diagnose eller hovedårsaken til klinisk vurdering. Ikke legg til informasjon som kan identifisere pasienten.", "確定診断または主な臨床的理由を入力してください。患者を特定できる情報は追加しないでください。", "输入已确认的诊断或主要临床原因。请勿添加可识别患者身份的信息。", "יש להזין אבחנה מאומתת או את הסיבה הקלינית העיקרית. אין להוסיף מידע המאפשר לזהות את המטופל."),
row("form.help.analyze", "ClinIA suggests options and references to verify. It does not make a final diagnosis or prescribe; the physician remains responsible for the decision.", "ClinIA propone opciones y referencias que verificar. No establece un diagnóstico definitivo ni prescribe; la decisión sigue correspondiendo al médico.", "ClinIA는 확인할 선택지와 참고자료를 제안합니다. 최종 진단을 내리거나 처방하지 않으며 결정은 의사에게 있습니다.", "ClinIA đề xuất các lựa chọn và tài liệu tham khảo cần xác minh. ClinIA không đưa ra chẩn đoán cuối cùng hay kê đơn; quyết định vẫn thuộc về bác sĩ.", "ClinIA foreslår alternativer og referanser som må kontrolleres. Det stiller ikke endelig diagnose eller forskriver; avgjørelsen ligger fortsatt hos legen.", "ClinIAは確認すべき選択肢と参考文献を提案します。最終診断や処方は行わず、判断は医師に委ねられます。", "ClinIA 提出需要核查的选项和参考资料，不作最终诊断或开具处方；决定仍由医生作出。", "ClinIA מציעה אפשרויות ומקורות לבדיקה. היא אינה קובעת אבחנה סופית או נותנת מרשם; ההחלטה נשארת בידי הרופא."),
row("form.countryLabel", "Patient country", "País del paciente", "환자 국가", "Quốc gia của bệnh nhân", "Pasientens land", "患者の国", "患者所在国家", "מדינת המטופל"),
row("form.countryPlaceholder", "Select a country", "Seleccionar un país", "국가 선택", "Chọn quốc gia", "Velg et land", "国を選択", "选择国家", "בחירת מדינה"),
row("form.countryHelp", "The country is preselected from browser settings when that information is available.", "El país se preselecciona a partir de la configuración del navegador cuando está disponible.", "정보가 있으면 브라우저 설정에서 국가를 미리 선택합니다.", "Quốc gia được chọn sẵn từ cài đặt trình duyệt khi thông tin này có sẵn.", "Landet forhåndsvelges fra nettleserinnstillingene når informasjonen er tilgjengelig.", "情報が利用できる場合は、ブラウザ設定から国を事前選択します。", "如有相关信息，将根据浏览器设置预选国家。", "המדינה נבחרת מראש מתוך הגדרות הדפדפן כאשר המידע זמין."),
row("form.detectedCountryPrefix", "Country detected by browser:", "País detectado por el navegador:", "브라우저가 감지한 국가:", "Quốc gia được trình duyệt phát hiện:", "Land oppdaget av nettleseren:", "ブラウザが検出した国：", "浏览器检测到的国家：", "המדינה שזוהתה בדפדפן:"),
row("form.jsonImportLabel", "Import a JSON object", "Importar un objeto JSON", "JSON 객체 가져오기", "Nhập đối tượng JSON", "Importer et JSON-objekt", "JSONオブジェクトをインポート", "导入 JSON 对象", "ייבוא אובייקט JSON"),
row("form.jsonImportHelp", "Paste a JSON object compatible with the clinical data here to prefill the form.", "Pegue aquí un objeto JSON compatible con los datos clínicos para rellenar el formulario.", "양식을 미리 채우려면 임상 데이터와 호환되는 JSON 객체를 여기에 붙여 넣으세요.", "Dán đối tượng JSON tương thích với dữ liệu lâm sàng vào đây để điền sẵn biểu mẫu.", "Lim inn et JSON-objekt som er kompatibelt med kliniske data for å forhåndsutfylle skjemaet.", "フォームを自動入力するため、臨床データと互換性のあるJSONオブジェクトをここに貼り付けてください。", "在此粘贴与临床数据兼容的 JSON 对象以预填表单。", "יש להדביק כאן אובייקט JSON התואם לנתונים הקליניים כדי למלא מראש את הטופס."),
row("form.jsonImportPlaceholder", '{ "age": 55, "sex": "male", "diagnosis": "Type 2 diabetes" }', '{ "age": 55, "sex": "male", "diagnosis": "Diabetes tipo 2" }', '{ "age": 55, "sex": "male", "diagnosis": "제2형 당뇨병" }', '{ "age": 55, "sex": "male", "diagnosis": "Tiểu đường loại 2" }', '{ "age": 55, "sex": "male", "diagnosis": "Diabetes type 2" }', '{ "age": 55, "sex": "male", "diagnosis": "2型糖尿病" }', '{ "age": 55, "sex": "male", "diagnosis": "2型糖尿病" }', '{ "age": 55, "sex": "male", "diagnosis": "סוכרת מסוג 2" }'),
row("form.jsonImportAction", "Load JSON into the form", "Cargar JSON en el formulario", "양식에 JSON 불러오기", "Nạp JSON vào biểu mẫu", "Last JSON inn i skjemaet", "JSONをフォームに読み込む", "将 JSON 加载到表单", "טעינת JSON לטופס"),
row("form.jsonImportSuccess", "The form was filled from the JSON.", "El formulario se rellenó a partir del JSON.", "JSON에서 양식이 채워졌습니다.", "Biểu mẫu đã được điền từ JSON.", "Skjemaet ble utfylt fra JSON.", "JSONからフォームを入力しました。", "已根据 JSON 填写表单。", "הטופס מולא מתוך ה־JSON."),
row("form.jsonImportInvalid", "Invalid or incompatible JSON. Check the object's syntax and structure.", "JSON no válido o incompatible. Revise la sintaxis y la estructura del objeto.", "JSON이 올바르지 않거나 호환되지 않습니다. 객체의 구문과 구조를 확인하세요.", "JSON không hợp lệ hoặc không tương thích. Kiểm tra cú pháp và cấu trúc đối tượng.", "Ugyldig eller inkompatibel JSON. Kontroller objektets syntaks og struktur.", "JSONが無効または互換性がありません。構文とオブジェクトの構造を確認してください。", "JSON 无效或不兼容。请检查对象的语法和结构。", "JSON אינו תקין או אינו תואם. יש לבדוק את התחביר ואת מבנה האובייקט."),
row("form.comparisonToggle", "Visual comparison mode", "Modo de comparación visual", "시각적 비교 모드", "Chế độ so sánh trực quan", "Visuell sammenligningsmodus", "視覚的比較モード", "可视比较模式", "מצב השוואה חזותית"),
row("form.comparisonHelp", "Paste two JSON objects to visually compare two patient summaries generated by ClinIA.", "Pegue dos objetos JSON para comparar visualmente dos resúmenes de pacientes generados por ClinIA.", "ClinIA가 생성한 두 환자 요약을 시각적으로 비교하려면 JSON 객체 두 개를 붙여 넣으세요.", "Dán hai đối tượng JSON để so sánh trực quan hai tóm tắt bệnh nhân do ClinIA tạo.", "Lim inn to JSON-objekter for å sammenligne to pasientsammendrag generert av ClinIA visuelt.", "ClinIAが生成した2つの患者サマリーを視覚的に比較するため、2つのJSONオブジェクトを貼り付けてください。", "粘贴两个 JSON 对象，以直观比较 ClinIA 生成的两份患者摘要。", "יש להדביק שני אובייקטי JSON להשוואה חזותית של שני סיכומי מטופלים שנוצרו ב־ClinIA."),
row("form.comparisonCaseOneLabel", "Case 1 JSON", "JSON del caso 1", "사례 1 JSON", "JSON ca 1", "JSON tilfelle 1", "症例1のJSON", "病例 1 JSON", "JSON מקרה 1"),
row("form.comparisonCaseTwoLabel", "Case 2 JSON", "JSON del caso 2", "사례 2 JSON", "JSON ca 2", "JSON tilfelle 2", "症例2のJSON", "病例 2 JSON", "JSON מקרה 2"),
row("form.comparisonLoadCaseOne", "Load case 1", "Cargar caso 1", "사례 1 불러오기", "Nạp ca 1", "Last tilfelle 1", "症例1を読み込む", "加载病例 1", "טעינת מקרה 1"),
row("form.comparisonLoadCaseTwo", "Load case 2", "Cargar caso 2", "사례 2 불러오기", "Nạp ca 2", "Last tilfelle 2", "症例2を読み込む", "加载病例 2", "טעינת מקרה 2"),
row("form.comparisonLoadHelp", "Use these buttons to quickly load two example JSON objects into the Case 1 and Case 2 areas before comparing.", "Use estos botones para cargar rápidamente dos JSON de ejemplo en las áreas Caso 1 y Caso 2 antes de comparar.", "비교하기 전에 이 버튼으로 두 예제 JSON을 사례 1 및 사례 2 영역에 빠르게 불러오세요.", "Dùng các nút này để nhanh chóng nạp hai JSON ví dụ vào vùng Ca 1 và Ca 2 trước khi so sánh.", "Bruk knappene til å laste to JSON-eksempler raskt inn i områdene Tilfelle 1 og Tilfelle 2 før sammenligning.", "比較前に、これらのボタンで2つのJSON例を症例1と症例2の欄にすばやく読み込めます。", "使用这些按钮，在比较前将两个示例 JSON 快速加载到病例 1 和病例 2 区域。", "יש להשתמש בכפתורים לטעינה מהירה של שני אובייקטי JSON לדוגמה באזורי מקרה 1 ומקרה 2 לפני ההשוואה."),
row("form.comparisonModalTitleCaseOne", "Edit JSON — Case 1", "Editar JSON — Caso 1", "JSON 편집 — 사례 1", "Chỉnh sửa JSON — Ca 1", "Rediger JSON — Tilfelle 1", "JSONを編集 — 症例1", "编辑 JSON — 病例 1", "עריכת JSON — מקרה 1"),
row("form.comparisonModalTitleCaseTwo", "Edit JSON — Case 2", "Editar JSON — Caso 2", "JSON 편집 — 사례 2", "Chỉnh sửa JSON — Ca 2", "Rediger JSON — Tilfelle 2", "JSONを編集 — 症例2", "编辑 JSON — 病例 2", "עריכת JSON — מקרה 2"),
row("form.comparisonModalDescription", "You can freely adjust this JSON before loading it into the corresponding comparison area.", "Puede ajustar libremente este JSON antes de cargarlo en el área de comparación correspondiente.", "해당 비교 영역에 불러오기 전에 이 JSON을 자유롭게 수정할 수 있습니다.", "Bạn có thể tự do chỉnh sửa JSON này trước khi nạp vào vùng so sánh tương ứng.", "Du kan justere JSON fritt før det lastes inn i det tilhørende sammenligningsområdet.", "対応する比較欄に読み込む前に、このJSONを自由に調整できます。", "您可以在加载到相应比较区域之前自由调整此 JSON。", "ניתן לערוך את ה־JSON בחופשיות לפני טעינתו באזור ההשוואה המתאים."),
row("form.comparisonModalSave", "Load this JSON", "Cargar este JSON", "이 JSON 불러오기", "Nạp JSON này", "Last denne JSON-en", "このJSONを読み込む", "加载此 JSON", "טעינת JSON זה"),
row("form.comparisonMedicationLabel", "Current medication", "Medicación actual", "현재 약물", "Thuốc hiện tại", "Nåværende legemiddel", "現在の薬剤", "当前药物", "טיפול תרופתי נוכחי"),
row("form.comparisonMedicationHelp", "You can choose several treatments to represent the same patient.", "Puede elegir varios tratamientos para representar al mismo paciente.", "동일한 환자를 나타내기 위해 여러 치료를 선택할 수 있습니다.", "Bạn có thể chọn nhiều phương pháp điều trị để mô tả cùng một bệnh nhân.", "Du kan velge flere behandlinger for å representere den samme pasienten.", "同じ患者を表すため、複数の治療を選択できます。", "您可以选择多种治疗来描述同一患者。", "ניתן לבחור כמה טיפולים כדי לייצג את אותו מטופל."),
row("form.comparisonMedicationOptions.metformin", "Metformin", "Metformina", "메트포르민", "Metformin", "Metformin", "メトホルミン", "二甲双胍", "מטפורמין"),
row("form.comparisonMedicationOptions.gliclazide", "Gliclazide", "Gliclazida", "글리클라지드", "Gliclazide", "Gliklazid", "グリクラジド", "格列齐特", "גליקלאזיד"),
row("form.comparisonMedicationOptions.empagliflozin", "Empagliflozin", "Empagliflozina", "엠파글리플로진", "Empagliflozin", "Empagliflozin", "エンパグリフロジン", "恩格列净", "אמפגליפלוזין"),
row("form.comparisonMedicationOptions.sitagliptin", "Sitagliptin", "Sitagliptina", "시타글립틴", "Sitagliptin", "Sitagliptin", "シタグリプチン", "西格列汀", "סיטגליפטין"),
row("form.comparisonMedicationOptions.semaglutide", "Semaglutide", "Semaglutida", "세마글루타이드", "Semaglutide", "Semaglutid", "セマグルチド", "司美格鲁肽", "סמגלוטייד"),
row("form.comparisonAction", "Compare the 2 cases", "Comparar los 2 casos", "두 사례 비교", "So sánh 2 ca", "Sammenlign de 2 tilfellene", "2つの症例を比較", "比较两个病例", "השוואת שני המקרים"),
row("form.comparisonSuccess", "Both cases were loaded for comparison.", "Se cargaron ambos casos para comparar.", "비교를 위해 두 사례가 불러와졌습니다.", "Đã nạp cả hai ca để so sánh.", "Begge tilfellene ble lastet for sammenligning.", "比較用に両方の症例を読み込みました。", "已加载两个病例进行比较。", "שני המקרים נטענו להשוואה."),
row("form.comparisonInvalid", "Unable to load both cases. Check the two JSON objects.", "No se pudieron cargar ambos casos. Revise los dos objetos JSON.", "두 사례를 불러올 수 없습니다. 두 JSON 객체를 확인하세요.", "Không thể nạp cả hai ca. Kiểm tra hai đối tượng JSON.", "Kan ikke laste begge tilfellene. Kontroller de to JSON-objektene.", "両方の症例を読み込めません。2つのJSONオブジェクトを確認してください。", "无法加载两个病例。请检查两个 JSON 对象。", "לא ניתן לטעון את שני המקרים. יש לבדוק את שני אובייקטי ה־JSON."),
row("form.ethnicityLabel", "Patient ethnicity", "Origen étnico del paciente", "환자 민족", "Dân tộc của bệnh nhân", "Pasientens etnisitet", "患者の民族的背景", "患者族裔", "מוצא אתני של המטופל"),
row("form.ethnicityHelp", "Select the ethnicity most relevant to the clinical context, if known.", "Seleccione el origen étnico más pertinente para el contexto clínico, si se conoce.", "알려진 경우 임상 상황에 가장 적절한 민족을 선택하세요.", "Chọn dân tộc phù hợp nhất với bối cảnh lâm sàng, nếu biết.", "Velg den etnisiteten som er mest relevant for den kliniske konteksten, hvis kjent.", "分かる場合は、臨床的背景に最も関連する民族的背景を選択してください。", "如已知，请选择与临床背景最相关的族裔。", "יש לבחור את המוצא האתני המתאים ביותר להקשר הקליני, אם ידוע."),
row("form.ageRange", "Allowed range: 0 to 130 years.", "Intervalo permitido: de 0 a 130 años.", "허용 범위: 0~130세.", "Khoảng cho phép: 0 đến 130 tuổi.", "Tillatt område: 0 til 130 år.", "許容範囲：0～130歳。", "允许范围：0 至 130 岁。", "טווח מותר: 0 עד 130 שנים."),
row("form.weightRange", "Allowed range: 0.5 to 500 kg.", "Intervalo permitido: de 0,5 a 500 kg.", "허용 범위: 0.5~500 kg.", "Khoảng cho phép: 0,5 đến 500 kg.", "Tillatt område: 0,5 til 500 kg.", "許容範囲：0.5～500 kg。", "允许范围：0.5 至 500 kg。", "טווח מותר: 0.5 עד 500 ק״ג."),
row("form.heightRange", "Allowed range: 20 to 300 cm.", "Intervalo permitido: de 20 a 300 cm.", "허용 범위: 20~300 cm.", "Khoảng cho phép: 20 đến 300 cm.", "Tillatt område: 20 til 300 cm.", "許容範囲：20～300 cm。", "允许范围：20 至 300 cm。", "טווח מותר: 20 עד 300 ס״מ."),
row("form.rangeError", "Value outside the allowed range.", "Valor fuera del intervalo permitido.", "허용 범위를 벗어난 값입니다.", "Giá trị ngoài khoảng cho phép.", "Verdien er utenfor tillatt område.", "値が許容範囲外です。", "数值超出允许范围。", "הערך מחוץ לטווח המותר."),
row("form.ethnicityOptions.caucasian", "Caucasian", "Caucásico", "백인", "Người da trắng", "Kaukasisk", "コーカサス系", "白人", "ממוצא אירופי"),
row("form.ethnicityOptions.black", "Black", "Negro", "흑인", "Người da đen", "Svart", "黒人", "黑人", "שחור"),
row("form.ethnicityOptions.asian", "Asian", "Asiático", "아시아인", "Người châu Á", "Asiatisk", "アジア系", "亚裔", "אסייתי"),
row("form.ethnicityOptions.hispanicLatino", "Hispanic or Latino", "Hispano o latino", "히스패닉 또는 라틴계", "Người gốc Tây Ban Nha hoặc Latinh", "Hispanisk eller latinamerikansk", "ヒスパニックまたはラテン系", "西班牙裔或拉丁裔", "היספני או לטיני"),
row("form.ethnicityOptions.middleEasternNorthAfrican", "Middle Eastern or North African", "De Oriente Medio o África del Norte", "중동 또는 북아프리카인", "Người Trung Đông hoặc Bắc Phi", "Fra Midtøsten eller Nord-Afrika", "中東系または北アフリカ系", "中东裔或北非裔", "מזרח תיכוני או צפון אפריקאי"),
row("form.ethnicityOptions.indigenous", "Indigenous", "Indígena", "원주민", "Người bản địa", "Urfolk", "先住民族", "原住民", "ילידי"),
row("form.ethnicityOptions.southAsian", "South Asian", "Surasiático", "남아시아인", "Người Nam Á", "Sørasiatisk", "南アジア系", "南亚裔", "דרום אסייתי"),
row("form.ethnicityOptions.southeastAsian", "Southeast Asian", "Del sudeste asiático", "동남아시아인", "Người Đông Nam Á", "Sørøstasiatisk", "東南アジア系", "东南亚裔", "דרום־מזרח אסייתי"),
row("form.ethnicityOptions.mixed", "Mixed", "Mixto", "혼합", "Hỗn hợp", "Blandet", "混合", "混合族裔", "מעורב"),
row("form.ethnicityOptions.other", "Other", "Otro", "기타", "Khác", "Annet", "その他", "其他", "אחר"),
row("form.ethnicityOptions.preferNotToSay", "Prefer not to answer", "Prefiero no responder", "응답하지 않음", "Không muốn trả lời", "Ønsker ikke å svare", "回答しない", "不愿回答", "מעדיף לא לענות"),
row("form.diabetesParamsTitle", "Quick parameters — Type 2 diabetes", "Parámetros rápidos — Diabetes tipo 2", "빠른 매개변수 — 제2형 당뇨병", "Thông số nhanh — Tiểu đường loại 2", "Hurtigparametere — Diabetes type 2", "簡易パラメータ — 2型糖尿病", "快捷参数 — 2型糖尿病", "פרמטרים מהירים — סוכרת מסוג 2"),
row("form.diabetesParamsOpenHint", "Quickly prefill the clinical parameters relevant to type 2 diabetes.", "Rellene rápidamente los parámetros clínicos pertinentes para la diabetes tipo 2.", "제2형 당뇨병에 유용한 임상 매개변수를 빠르게 미리 입력하세요.", "Điền sẵn nhanh các thông số lâm sàng hữu ích cho tiểu đường loại 2.", "Forhåndsutfyll raskt de kliniske parameterne som er relevante for diabetes type 2.", "2型糖尿病に関連する臨床パラメータをすばやく入力します。", "快速预填与2型糖尿病相关的临床参数。", "מילוי מהיר מראש של הפרמטרים הקליניים הרלוונטיים לסוכרת מסוג 2."),
row("form.diabetesParamsEditableHint", "You can then adjust them to the patient's profile.", "Después puede ajustarlos al perfil del paciente.", "그런 다음 환자 프로필에 맞게 조정할 수 있습니다.", "Sau đó bạn có thể điều chỉnh theo hồ sơ bệnh nhân.", "Du kan deretter tilpasse dem til pasientens profil.", "その後、患者のプロフィールに合わせて調整できます。", "随后可根据患者情况进行调整。", "לאחר מכן ניתן להתאים אותם לפרופיל המטופל."),
row("form.diabetesParamsAnalyzeHint", "When everything is ready, click Analyze.", "Cuando todo esté listo, haga clic en Analizar.", "모든 준비가 되면 분석을 클릭하세요.", "Khi mọi thứ đã sẵn sàng, nhấn Phân tích.", "Når alt er klart, klikker du på Analyser.", "準備ができたら「分析」をクリックしてください。", "准备就绪后，点击“分析”。", "כשהכול מוכן, יש ללחוץ על ניתוח."),
row("comparison.quickViewTitle", "Quick view of clinical differences", "Vista rápida de las diferencias clínicas", "임상 차이 빠르게 보기", "Xem nhanh khác biệt lâm sàng", "Hurtigoversikt over kliniske forskjeller", "臨床的な違いの簡易表示", "临床差异速览", "מבט מהיר על ההבדלים הקליניים"),
row("comparison.quickViewHelp", "This summary highlights the most useful differences to guide reading before the full details.", "Este resumen destaca las diferencias más útiles para orientar la lectura antes de los detalles completos.", "이 요약은 전체 세부 정보를 읽기 전에 가장 유용한 차이를 강조합니다.", "Tóm tắt này nêu bật những khác biệt hữu ích nhất để định hướng trước khi đọc toàn bộ chi tiết.", "Sammendraget fremhever de mest nyttige forskjellene for å veilede lesingen før de fullstendige detaljene.", "この概要は、詳細を読む前に把握すべき重要な違いを示します。", "此摘要突出最有用的差异，以在查看完整详情前引导阅读。", "הסיכום מדגיש את ההבדלים השימושיים ביותר להכוונת הקריאה לפני הפרטים המלאים."),
row("comparison.mobileFocusTitle", "Essential mobile view", "Vista móvil esencial", "모바일 핵심 보기", "Xem nội dung thiết yếu trên di động", "Viktig mobiloversikt", "モバイル用の要点表示", "移动端要点视图", "תצוגת עיקרי הדברים בנייד"),
row("comparison.mobileFocusHelp", "On a phone, ClinIA keeps only the most useful points for a quick scan.", "En el teléfono, ClinIA conserva solo los puntos más útiles para una lectura rápida.", "휴대전화에서는 빠르게 살펴볼 수 있도록 ClinIA가 가장 유용한 핵심 사항만 표시합니다.", "Trên điện thoại, ClinIA chỉ giữ những điểm hữu ích nhất để xem nhanh.", "På telefon viser ClinIA bare de mest nyttige punktene for en rask gjennomgang.", "スマートフォンでは、ClinIAはすばやく確認できる最も重要な点のみを表示します。", "在手机上，ClinIA 仅保留最有用的要点以便快速浏览。", "בטלפון, ClinIA מציגה רק את הנקודות השימושיות ביותר לסקירה מהירה."),
row("comparison.mobileDrillDownHint", "Open the full details to review clinical differences, points requiring attention and the underlying reasoning.", "Abra los detalles completos para consultar las diferencias clínicas, los puntos de atención y el razonamiento subyacente.", "전체 세부 정보를 열어 임상 차이, 주의 사항 및 근거를 확인하세요.", "Mở toàn bộ chi tiết để xem khác biệt lâm sàng, các điểm cần chú ý và lập luận bên dưới.", "Åpne de fullstendige detaljene for å se kliniske forskjeller, oppmerksomhetspunkter og den underliggende begrunnelsen.", "詳細を開くと、臨床的な違い、注意点、その根拠を確認できます。", "打开完整详情以查看临床差异、注意事项及相关推理。", "יש לפתוח את הפרטים המלאים כדי לעיין בהבדלים הקליניים, בנקודות לתשומת לב ובנימוקים."),
row("comparison.mobileExpand", "Tap to open", "Toque para abrir", "탭하여 열기", "Chạm để mở", "Trykk for å åpne", "タップして開く", "点击展开", "הקשה לפתיחה"),
row("comparison.mobileCollapse", "Tap to collapse", "Toque para contraer", "탭하여 접기", "Chạm để thu gọn", "Trykk for å lukke", "タップして折りたたむ", "点击收起", "הקשה לצמצום"),
row("comparison.mobileDifferencesTitle", "Major differences", "Diferencias principales", "주요 차이", "Khác biệt chính", "Store forskjeller", "主な違い", "主要差异", "הבדלים עיקריים"),
row("comparison.mobileFocusCaseOne", "Case 1", "Caso 1", "사례 1", "Ca 1", "Tilfelle 1", "症例1", "病例 1", "מקרה 1"),
row("comparison.mobileFocusCaseTwo", "Case 2", "Caso 2", "사례 2", "Ca 2", "Tilfelle 2", "症例2", "病例 2", "מקרה 2"),
row("comparison.quickViewAgeLabel", "Age", "Edad", "나이", "Tuổi", "Alder", "年齢", "年龄", "גיל"),
row("comparison.quickViewSexLabel", "Sex", "Sexo", "성별", "Giới tính", "Kjønn", "性別", "性别", "מין"),
row("comparison.quickViewCardioRiskLabel", "Cardiorenal risk", "Riesgo cardiorrenal", "심장·신장 위험", "Nguy cơ tim-thận", "Kardiorenal risiko", "心腎リスク", "心肾风险", "סיכון לבבי־כלייתי"),
row("comparison.quickViewRenalLabel", "Kidney function", "Función renal", "신장 기능", "Chức năng thận", "Nyrefunksjon", "腎機能", "肾功能", "תפקוד כלייתי"),
row("comparison.quickViewFragilityLabel", "Frailty", "Fragilidad", "노쇠", "Tình trạng suy yếu", "Skrøpelighet", "フレイル", "衰弱", "שבריריות"),
row("comparison.quickViewNotSpecified", "Not specified", "No especificado", "명시되지 않음", "Chưa xác định", "Ikke oppgitt", "未指定", "未指定", "לא צוין"),
row("comparison.quickViewDifferenceBadge", "Clear difference", "Diferencia clara", "뚜렷한 차이", "Khác biệt rõ ràng", "Tydelig forskjell", "明確な違い", "明显差异", "הבדל ברור"),
row("comparison.quickViewMajorDifferenceBadge", "Marked contrast", "Contraste marcado", "현저한 대비", "Tương phản rõ rệt", "Markert kontrast", "顕著な対比", "显著对比", "ניגוד בולט"),
row("comparison.microSummaryTitle", "At-a-glance micro-summary", "Microrresumen de lectura rápida", "한눈에 보는 짧은 요약", "Tóm tắt cực ngắn để xem nhanh", "Mikrosammendrag for rask oversikt", "ひと目で分かる短い要約", "一目了然的微摘要", "תמצית לסקירה מהירה"),
row("comparison.microSummaryHelp", "Three very short points to quickly understand the profile before the detailed text.", "Tres puntos muy breves para entender rápidamente el perfil antes del texto detallado.", "상세 텍스트를 읽기 전에 프로필을 빠르게 이해할 수 있는 세 가지 짧은 핵심 사항입니다.", "Ba điểm rất ngắn để nhanh chóng hiểu hồ sơ trước khi đọc nội dung chi tiết.", "Tre svært korte punkter for raskt å forstå profilen før den detaljerte teksten.", "詳細な文章の前にプロフィールをすばやく把握するための3つの短い要点です。", "三个简短要点，帮助在阅读详细文本前快速理解患者情况。", "שלוש נקודות קצרות מאוד להבנת הפרופיל במהירות לפני הטקסט המפורט."),
row("comparison.microSummaryProfilePrefix", "Profile", "Perfil", "프로필", "Hồ sơ", "Profil", "プロフィール", "概况", "פרופיל"),
row("comparison.microSummaryPriorityPrefix", "Priority", "Prioridad", "우선순위", "Ưu tiên", "Prioritet", "優先事項", "优先事项", "עדיפות"),
row("comparison.microSummaryCautionPrefix", "Caution", "Precaución", "주의", "Thận trọng", "Forsiktighet", "注意", "注意", "זהירות"),
row("comparison.microSummaryAgeOlder", "older", "de mayor edad", "더 고령", "lớn tuổi hơn", "eldre", "より高齢", "年龄较大", "מבוגר יותר"),
row("comparison.microSummaryAgeYounger", "younger", "más joven", "더 젊음", "trẻ hơn", "yngre", "より若い", "年龄较小", "צעיר יותר"),
row("comparison.microSummaryFragilityHigh", "frail", "frágil", "노쇠", "suy yếu", "skrøpelig", "フレイルあり", "衰弱", "שברירי"),
row("comparison.microSummaryFragilityLow", "low frailty", "poca fragilidad", "노쇠 정도 낮음", "ít suy yếu", "lite skrøpelig", "フレイルが軽度", "衰弱程度较低", "שבריריות נמוכה"),
row("comparison.microSummaryFragilityNeutral", "frailty to clarify", "fragilidad por precisar", "노쇠 정도 확인 필요", "cần xác định tình trạng suy yếu", "skrøpelighet må avklares", "フレイルの確認が必要", "衰弱程度待确认", "שבריריות לבירור"),
row("comparison.microSummaryCardioHigh", "high cardiorenal risk", "riesgo cardiorrenal alto", "높은 심장·신장 위험", "nguy cơ tim-thận cao", "høy kardiorenal risiko", "心腎リスクが高い", "心肾风险较高", "סיכון לבבי־כלייתי גבוה"),
row("comparison.microSummaryCardioModerate", "intermediate cardiorenal risk", "riesgo cardiorrenal intermedio", "중간 심장·신장 위험", "nguy cơ tim-thận trung bình", "middels kardiorenal risiko", "心腎リスクが中等度", "心肾风险中等", "סיכון לבבי־כלייתי בינוני"),
row("comparison.microSummaryCardioNeutral", "cardiorenal risk to clarify", "riesgo cardiorrenal por precisar", "심장·신장 위험 확인 필요", "cần xác định nguy cơ tim-thận", "kardiorenal risiko må avklares", "心腎リスクの確認が必要", "心肾风险待确认", "סיכון לבבי־כלייתי לבירור"),
row("comparison.microSummaryPriorityCardio", "focus on reading about cardiorenal benefit", "priorizar la lectura sobre el beneficio cardiorrenal", "심장·신장 이점에 관한 내용 우선 검토", "ưu tiên đọc về lợi ích tim-thận", "prioriter lesing om kardiorenal nytte", "心腎への利益に関する情報を優先して読む", "优先阅读心肾获益相关信息", "עדיפות לקריאה על התועלת הלבבית־כלייתית"),
row("comparison.microSummaryPriorityFrailty", "focus on reading about tolerability and safety", "priorizar la lectura sobre tolerancia y seguridad", "내약성 및 안전성에 관한 내용 우선 검토", "ưu tiên đọc về khả năng dung nạp và an toàn", "prioriter lesing om toleranse og sikkerhet", "忍容性と安全性に関する情報を優先して読む", "优先阅读耐受性和安全性相关信息", "עדיפות לקריאה על סבילות ובטיחות"),
row("comparison.microSummaryPriorityGlycemia", "focus on reading about overall glycemic control", "priorizar la lectura sobre el control glucémico global", "전반적인 혈당 조절에 관한 내용 우선 검토", "ưu tiên đọc về kiểm soát đường huyết tổng thể", "prioriter lesing om samlet blodsukkerkontroll", "全体的な血糖管理に関する情報を優先して読む", "优先阅读整体血糖控制相关信息", "עדיפות לקריאה על איזון כללי של רמות הסוכר"),
row("comparison.primaryAlertTitle", "Main point requiring attention", "Principal punto de atención", "주요 주의 사항", "Điểm chính cần chú ý", "Viktigste oppmerksomhetspunkt", "主な注意点", "主要注意事项", "נקודה עיקרית לתשומת לב"),
row("comparison.primaryAlertKidneyIcon", "Renal", "Renal", "신장", "Thận", "Nyre", "腎", "肾脏", "כלייתי"),
row("comparison.primaryAlertCardioIcon", "Cardiorenal", "Cardiorrenal", "심장·신장", "Tim-thận", "Kardiorenal", "心腎", "心肾", "לבבי־כלייתי"),
row("comparison.primaryAlertGeneralIcon", "Context", "Contexto", "상황", "Bối cảnh", "Kontekst", "背景", "背景", "הקשר"),
row("comparison.primaryAlertKidney", "check kidney function first before weighing the options", "verificar primero la función renal antes de ponderar las opciones", "선택지를 평가하기 전에 신장 기능 우선 확인", "ưu tiên kiểm tra chức năng thận trước khi cân nhắc các lựa chọn", "kontroller nyrefunksjonen først før alternativene vurderes", "選択肢を評価する前に腎機能を優先して確認する", "权衡选项前应优先检查肾功能", "יש לבדוק תחילה את התפקוד הכלייתי לפני שקלול האפשרויות"),
row("comparison.primaryAlertFrailty", "keep high frailty in focus when reviewing the case", "mantener la fragilidad elevada en primer plano al revisar el caso", "사례 검토 시 높은 노쇠 정도를 우선 고려", "chú trọng tình trạng suy yếu cao khi xem xét ca bệnh", "ha høy skrøpelighet i fokus ved gjennomgang av tilfellet", "症例を読む際は高度のフレイルに重点を置く", "审阅病例时应重点关注高度衰弱", "יש לתת מקום מרכזי לשבריריות גבוהה בקריאת המקרה"),
row("comparison.primaryAlertCardio", "keep the dominant cardiorenal risk in focus when reviewing the case", "mantener el riesgo cardiorrenal dominante en primer plano al revisar el caso", "사례 검토 시 주된 심장·신장 위험을 우선 고려", "chú trọng nguy cơ tim-thận chiếm ưu thế khi xem xét ca bệnh", "ha den dominerende kardiorenale risikoen i fokus ved gjennomgang av tilfellet", "症例を読む際は主要な心腎リスクに重点を置く", "审阅病例时应重点关注占主导地位的心肾风险", "יש לתת מקום מרכזי לסיכון הלבבי־כלייתי הדומיננטי בקריאת המקרה"),
row("comparison.primaryAlertGeneral", "place the options in the overall clinical context before drawing conclusions", "situar las opciones en el contexto clínico global antes de concluir", "결론을 내리기 전에 전반적인 임상 상황에서 선택지 검토", "đặt các lựa chọn trong bối cảnh lâm sàng tổng thể trước khi kết luận", "sett alternativene inn i den samlede kliniske konteksten før konklusjoner trekkes", "結論を出す前に、選択肢を全体的な臨床背景に照らして検討する", "得出结论前应将选项置于整体临床背景中考量", "יש להציב את האפשרויות בהקשר הקליני הכולל לפני הסקת מסקנות"),
row("comparison.reverifyAction", "Rerun for verification (SUPERADMIN)", "Repetir para verificar (SUPERADMIN)", "검증을 위해 다시 실행 (SUPERADMIN)", "Chạy lại để xác minh (SUPERADMIN)", "Kjør på nytt for bekreftelse (SUPERADMIN)", "検証のため再実行（SUPERADMIN）", "重新运行以核查（SUPERADMIN）", "הפעלה מחדש לאימות (SUPERADMIN)"),
row("comparison.reverifyLoading", "OpenAI verification in progress...", "Verificación de OpenAI en curso...", "OpenAI 검증 진행 중...", "Đang xác minh bằng OpenAI...", "OpenAI-bekreftelse pågår...", "OpenAIによる検証中...", "正在通过 OpenAI 核查...", "אימות באמצעות OpenAI מתבצע..."),
row("comparison.microSummaryCautionRenal", "check kidney function before interpreting the options", "verificar la función renal antes de interpretar las opciones", "선택지를 해석하기 전에 신장 기능 확인", "kiểm tra chức năng thận trước khi diễn giải các lựa chọn", "kontroller nyrefunksjonen før alternativene tolkes", "選択肢を解釈する前に腎機能を確認する", "解读选项前应检查肾功能", "יש לבדוק תפקוד כלייתי לפני פירוש האפשרויות"),
row("comparison.microSummaryCautionFrailty", "monitor frailty and overall tolerability", "vigilar la fragilidad y la tolerancia global", "노쇠 및 전반적인 내약성 모니터링", "theo dõi tình trạng suy yếu và khả năng dung nạp tổng thể", "overvåk skrøpelighet og samlet toleranse", "フレイルと全体的な忍容性を確認する", "监测衰弱程度和整体耐受性", "יש לעקוב אחר השבריריות והסבילות הכללית"),
row("comparison.microSummaryCautionGeneral", "place the options in the full clinical context", "situar las opciones en el contexto clínico completo", "전체 임상 상황에서 선택지 검토", "đặt các lựa chọn trong bối cảnh lâm sàng đầy đủ", "sett alternativene inn i den fullstendige kliniske konteksten", "選択肢を臨床背景全体に照らして検討する", "将选项置于完整临床背景中考量", "יש להציב את האפשרויות בהקשר הקליני המלא"),
row("comparison.generatedSummaryTitle", "ClinIA-generated patient summary — visual comparison", "Resumen de paciente generado por ClinIA — comparación visual", "ClinIA 생성 환자 요약 — 시각적 비교", "Tóm tắt bệnh nhân do ClinIA tạo — so sánh trực quan", "Pasientsammendrag generert av ClinIA — visuell sammenligning", "ClinIAが生成した患者サマリー — 視覚的比較", "ClinIA 生成的患者摘要 — 可视比较", "סיכום מטופל שנוצר ב־ClinIA — השוואה חזותית"),
row("comparison.generatedSummaryHelp", "Two clinical profiles are analyzed side by side to visually compare the patient summary.", "Se analizan dos perfiles clínicos en paralelo para comparar visualmente el resumen del paciente.", "환자 요약을 시각적으로 비교하기 위해 두 임상 프로필을 나란히 분석합니다.", "Hai hồ sơ lâm sàng được phân tích song song để so sánh trực quan tóm tắt bệnh nhân.", "To kliniske profiler analyseres side om side for å sammenligne pasientsammendraget visuelt.", "2つの臨床プロフィールを並べて分析し、患者サマリーを視覚的に比較します。", "并排分析两个临床概况，以直观比较患者摘要。", "שני פרופילים קליניים מנותחים זה לצד זה להשוואה חזותית של סיכום המטופל."),
row("comparison.relevanceChartTitle", "Relative clinical relevance by age and context — visual comparison", "Relevancia clínica relativa según la edad y el contexto — comparación visual", "나이 및 상황에 따른 상대적 임상 관련성 — 시각적 비교", "Mức độ phù hợp lâm sàng tương đối theo tuổi và bối cảnh — so sánh trực quan", "Relativ klinisk relevans etter alder og kontekst — visuell sammenligning", "年齢と背景に応じた相対的な臨床的位置づけ — 視覚的比較", "按年龄和背景评估的相对临床相关性 — 可视比较", "רלוונטיות קלינית יחסית לפי גיל והקשר — השוואה חזותית"),
row("comparison.relevanceChartHelp", "Each profile shows its clinical chart, one below the other, to make visual comparison easier.", "Cada perfil muestra su cuadro clínico, uno debajo del otro, para facilitar la comparación visual.", "시각적 비교를 쉽게 하기 위해 각 프로필의 임상 차트를 위아래로 표시합니다.", "Mỗi hồ sơ hiển thị bảng lâm sàng của mình, xếp trên dưới để dễ so sánh trực quan.", "Hver profil viser sin kliniske oversikt, den ene under den andre, for å gjøre visuell sammenligning enklere.", "視覚的に比較しやすいよう、各プロフィールの臨床チャートを上下に表示します。", "每个概况的临床图表上下排列，以便直观比较。", "כל פרופיל מציג את התרשים הקליני שלו, זה מתחת לזה, כדי להקל על ההשוואה החזותית."),
row("comparison.fallbackHeading", "Clinical profile", "Perfil clínico", "임상 프로필", "Hồ sơ lâm sàng", "Klinisk profil", "臨床プロフィール", "临床概况", "פרופיל קליני"),
row("comparison.summaryUnavailable", "Summary unavailable.", "Resumen no disponible.", "요약을 사용할 수 없습니다.", "Tóm tắt không khả dụng.", "Sammendrag utilgjengelig.", "サマリーを利用できません。", "摘要不可用。", "הסיכום אינו זמין."),
row("comments.leaveCommentTooltip", "Click here to open the comments page, leave a support or follow-up message, then check replies later with your tracking code.", "Haga clic aquí para abrir la página de comentarios, dejar un mensaje de soporte o seguimiento y consultar las respuestas más tarde con su código de seguimiento.", "여기를 클릭하여 댓글 페이지를 열고 지원 또는 후속 메시지를 남긴 다음 추적 코드로 나중에 답변을 확인하세요.", "Nhấn vào đây để mở trang bình luận, để lại tin nhắn hỗ trợ hoặc theo dõi, rồi xem phản hồi sau bằng mã theo dõi của bạn.", "Klikk her for å åpne kommentarsiden, legge igjen en støtte- eller oppfølgingsmelding og se svar senere med sporingskoden din.", "ここをクリックしてコメントページを開き、サポートやフォローアップのメッセージを残してください。追跡コードで後から返信を確認できます。", "点击此处打开评论页面，留下支持或后续跟进消息，随后使用跟踪码查看回复。", "יש ללחוץ כאן לפתיחת עמוד התגובות, להשאיר הודעת תמיכה או מעקב ולבדוק תשובות בהמשך באמצעות קוד המעקב."),
row("comments.openaiModelTooltip", "Use this selector to choose the analysis model. Mini mode is usually faster and well suited to routine tests. The other model can provide a comparison if you want to see how the wording or response structure changes.", "Use este selector para elegir el modelo de análisis. El modo mini suele ser más rápido y adecuado para pruebas habituales. El otro modelo permite comparar cómo cambia la redacción o la estructura de la respuesta.", "이 선택기로 분석 모델을 선택하세요. mini 모드는 일반적으로 더 빠르며 일반적인 테스트에 적합합니다. 응답의 표현이나 구조가 어떻게 달라지는지 확인하려면 다른 모델을 비교 대상으로 사용할 수 있습니다.", "Dùng bộ chọn này để chọn mô hình phân tích. Chế độ mini thường nhanh hơn và phù hợp cho thử nghiệm thông thường. Mô hình còn lại có thể dùng để so sánh cách diễn đạt hoặc cấu trúc phản hồi thay đổi.", "Bruk velgeren til å velge analysemodell. Mini-modus er vanligvis raskere og passer til vanlige tester. Den andre modellen kan brukes til sammenligning for å se hvordan formuleringen eller svarstrukturen endres.", "この選択欄で分析モデルを選びます。miniモードは通常より速く、一般的な試験に適しています。表現や回答構造の変化を確認したい場合は、別のモデルを比較に使用できます。", "使用此选择器选择分析模型。mini 模式通常更快，适合常规测试。另一模型可用于比较措辞或回复结构的变化。", "יש להשתמש בבורר לבחירת מודל הניתוח. מצב mini בדרך כלל מהיר יותר ומתאים לבדיקות שגרתיות. המודל האחר יכול לשמש להשוואת שינויי ניסוח או מבנה התשובה."),
row("comments.exampleCaseTooltip", "Use this selector to load a prefilled clinical case. It helps you quickly explore ClinIA without entering all the data manually.", "Use este selector para cargar un caso clínico ya rellenado. Permite explorar rápidamente ClinIA sin introducir todos los datos a mano.", "이 선택기로 미리 입력된 임상 사례를 불러오세요. 모든 데이터를 수동으로 입력하지 않고 ClinIA를 빠르게 살펴볼 수 있습니다.", "Dùng bộ chọn này để nạp ca lâm sàng đã điền sẵn. Bạn có thể nhanh chóng khám phá ClinIA mà không cần nhập mọi dữ liệu bằng tay.", "Bruk velgeren til å laste et forhåndsutfylt klinisk tilfelle. Det lar deg raskt utforske ClinIA uten å registrere alle data manuelt.", "この選択欄で入力済みの症例を読み込めます。すべてのデータを手入力せず、ClinIAの使い方をすばやく確認できます。", "使用此选择器加载预填的临床病例，无需手动输入所有数据即可快速了解 ClinIA。", "יש להשתמש בבורר לטעינת מקרה קליני שמולא מראש. כך ניתן להכיר את ClinIA במהירות בלי להזין ידנית את כל הנתונים."),
row("comments.replyLookupDescription", "Enter exactly the name or alias used for your comment, along with your tracking code. If your browser saved this information, it is prefilled automatically.", "Introduzca exactamente el nombre o seudónimo usado en el comentario y su código de seguimiento. Si el navegador guardó esta información, se rellenará automáticamente.", "댓글에 사용한 이름 또는 별칭과 추적 코드를 정확히 입력하세요. 브라우저에 이 정보가 저장되어 있으면 자동으로 입력됩니다.", "Nhập chính xác tên hoặc bí danh đã dùng khi bình luận cùng mã theo dõi. Nếu trình duyệt đã lưu thông tin này, thông tin sẽ được điền sẵn tự động.", "Angi nøyaktig navnet eller aliaset du brukte i kommentaren, sammen med sporingskoden. Hvis nettleseren lagret informasjonen, fylles den ut automatisk.", "コメント時に使用した名前または別名と追跡コードを正確に入力してください。ブラウザに保存されている場合は自動入力されます。", "准确输入评论时使用的姓名或昵称及跟踪码。如果浏览器已保存这些信息，将自动预填。", "יש להזין בדיוק את השם או הכינוי ששימש בתגובה, יחד עם קוד המעקב. אם הדפדפן שמר את המידע, הוא ימולא אוטומטית."),
row("comments.namePlaceholder", "Name or alias", "Nombre o seudónimo", "이름 또는 별칭", "Tên hoặc bí danh", "Navn eller alias", "名前または別名", "姓名或昵称", "שם או כינוי"),
row("comments.trackingCodePlaceholder", "Tracking code", "Código de seguimiento", "추적 코드", "Mã theo dõi", "Sporingskode", "追跡コード", "跟踪码", "קוד מעקב"),
row("comments.searchLoading", "Searching...", "Buscando...", "검색 중...", "Đang tìm...", "Søker...", "検索中...", "正在搜索...", "מחפש..."),
row("comments.viewReplies", "View my replies", "Ver mis respuestas", "내 답변 보기", "Xem phản hồi của tôi", "Se mine svar", "自分宛ての返信を表示", "查看我的回复", "הצגת התשובות שלי"),
row("comments.viewRepliesTooltip", "Click here to check whether the ClinIA team replied to your comments using your name or alias and tracking code.", "Haga clic aquí para comprobar si el equipo de ClinIA respondió a sus comentarios usando su nombre o seudónimo y código de seguimiento.", "여기를 클릭하여 이름 또는 별칭과 추적 코드로 ClinIA 팀이 댓글에 답변했는지 확인하세요.", "Nhấn vào đây để kiểm tra đội ngũ ClinIA đã trả lời bình luận của bạn chưa, bằng tên hoặc bí danh và mã theo dõi.", "Klikk her for å se om ClinIA-teamet har svart på kommentarene dine ved hjelp av navnet eller aliaset og sporingskoden.", "ここをクリックし、名前または別名と追跡コードを使ってClinIAチームからの返信を確認してください。", "点击此处，使用姓名或昵称及跟踪码检查 ClinIA 团队是否已回复您的评论。", "יש ללחוץ כאן כדי לבדוק אם צוות ClinIA השיב לתגובות שלך, באמצעות השם או הכינוי וקוד המעקב."),
row("comments.noRepliesFound", "No replies found for this tracking information.", "No se encontraron respuestas para esta información de seguimiento.", "이 추적 정보에 대한 답변을 찾을 수 없습니다.", "Không tìm thấy phản hồi cho thông tin theo dõi này.", "Ingen svar funnet for denne sporingsinformasjonen.", "この追跡情報に対応する返信は見つかりませんでした。", "未找到与此跟踪信息对应的回复。", "לא נמצאו תשובות עבור פרטי המעקב האלה."),
row("comments.commentCreatedAtPrefix", "Comment dated", "Comentario del", "댓글 작성일", "Bình luận ngày", "Kommentar fra", "コメント日", "评论日期", "תגובה מתאריך"),
row("comments.replyFromPrefix", "Reply from", "Respuesta de", "답변 작성자", "Phản hồi từ", "Svar fra", "返信者", "回复来自", "תשובה מאת"),
row("comments.replyFromSeparator", "on", "el", "작성일", "vào", "den", "日付", "于", "בתאריך"),
];

function leaves(value: unknown, prefix = ""): [string, string][] {
    if (typeof value === "string") return [[prefix, value]];
    return value && typeof value === "object" ? Object.entries(value).flatMap(([key, entry]) => leaves(entry, prefix ? `${prefix}.${key}` : key)) : [];
}
function dictionaryRows(getDictionary: (locale: string) => unknown): readonly string[][] {
    const dictionaries = languages.map(language => new Map(leaves(getDictionary(language))));
    return [...dictionaries[0]].flatMap(([key, source]) => {
        const translations = dictionaries.slice(1).map(dictionary => dictionary.get(key));
        return translations.every(value => validUiTranslation(source, value)) ? [[source, ...translations as string[]]] : [];
    });
}
const normalized = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
const candidates = [
    ...explicitRows, ...clinicalUiRows,
    ...dictionaryRows(getClinicalResultStrings),
    ...dictionaryRows(getClinicalFormReviewedStrings),
    ...dictionaryRows(getCachedResultNoticeLabels),
];
for (const entry of Object.values(compiled.byKey)) {
    const translations = languages.slice(1).map(language => (entry.translations as Record<string, string>)[language]);
    if (translations.every(value => validUiTranslation(entry.source, value))) candidates.push([entry.source, ...translations]);
}

// These reviewed form messages have the same meaning as their registry source.
// The source includes the old “Example case” control name; translations name the
// localized control instead. The French registry remains the authoritative key.
for (const key of ["exampleCaseRequiredHint", "exampleCaseSelectionRequired"] as const) {
    candidates.push([labels.form[key], ...languages.slice(1).map(language => getClinicalFormReviewedStrings(language)[key])]);
}

export const clinicalDemoUiRows: readonly (readonly string[])[] = [...new Set(leaves(labels).map(([, source]) => source))].flatMap(source => {
    const candidate = candidates.find(entry => normalized(entry[0]) === normalized(source));
    return candidate ? [[source, ...candidate.slice(1)]] : [];
});
const bySource = new Map(clinicalDemoUiRows.map(entry => [entry[0], entry]));
export function localizeClinicalDemoUiLabel(source: string, locale: string): string | null {
    const column = languages.indexOf(baseUiLocale(locale));
    return column >= 0 ? bySource.get(source)?.[column] ?? null : null;
}
