import { UI_LABELS_FR } from "./uiLabels.fr";
import { baseUiLocale } from "./uiLocales";

// FR, EN, ES, KO, VI, NO, JA, ZH, HE. Fixed interface text only.
export const coreUiRows: readonly (readonly string[])[] = [
    [UI_LABELS_FR.generalUi.error, "Unable to process this request. Check the information and contact administration if the problem persists.", "No se pudo procesar esta solicitud. Verifique los datos y contacte con la administración si el problema persiste.", "요청을 처리할 수 없습니다. 정보를 확인하고 문제가 지속되면 관리자에게 문의하세요.", "Không thể xử lý yêu cầu này. Hãy kiểm tra thông tin và liên hệ quản trị viên nếu vấn đề vẫn tiếp diễn.", "Kunne ikke behandle forespørselen. Kontroller informasjonen og kontakt administrasjonen hvis problemet vedvarer.", "この要求を処理できません。入力内容を確認し、問題が続く場合は管理者にお問い合わせください。", "无法处理此请求。请检查信息，如果问题仍然存在，请联系管理员。", "לא ניתן לעבד את הבקשה. יש לבדוק את הפרטים ולפנות למנהל אם הבעיה נמשכת."],
    [UI_LABELS_FR.generalUi.translating, "Translating the interface…", "Traduciendo la interfaz…", "인터페이스 번역 중…", "Đang dịch giao diện…", "Oversetter grensesnittet…", "画面を翻訳中…", "正在翻译界面…", "מתרגם את הממשק…"],
    [UI_LABELS_FR.generalUi.unknown, "Unknown", "Desconocido", "알 수 없음", "Không rõ", "Ukjent", "不明", "未知", "לא ידוע"],
    [UI_LABELS_FR.generalUi.passwordChangeFailed, "Unable to complete the password change.", "No se pudo completar el cambio de contraseña.", "비밀번호 변경을 완료할 수 없습니다.", "Không thể hoàn tất việc đổi mật khẩu.", "Kunne ikke fullføre passordendringen.", "パスワードの変更を完了できません。", "无法完成密码更改。", "לא ניתן להשלים את שינוי הסיסמה."],
    [UI_LABELS_FR.emailQuota.title, "Daily email quota", "Cuota diaria de correo", "일일 이메일 한도", "Hạn mức email hằng ngày", "Daglig e-postkvote", "1日のメール送信枠", "每日邮件配额", "מכסת דוא״ל יומית"],
    [UI_LABELS_FR.emailQuota.counter, "{count} / {limit} email attempts", "{count} / {limit} intentos de correo", "이메일 시도 {count} / {limit}", "{count} / {limit} lần thử gửi email", "{count} / {limit} e-postforsøk", "メール送信試行 {count} / {limit}", "邮件发送尝试 {count} / {limit}", "{count} / {limit} ניסיונות שליחת דוא״ל"],
    [UI_LABELS_FR.emailQuota.remaining, "{remaining} attempts remaining", "{remaining} intentos restantes", "남은 시도 {remaining}회", "Còn {remaining} lần thử", "{remaining} forsøk igjen", "残り {remaining} 回", "剩余 {remaining} 次尝试", "נותרו {remaining} ניסיונות"],
    [UI_LABELS_FR.emailQuota.day, "UTC day: {day}", "Día UTC: {day}", "UTC 날짜: {day}", "Ngày UTC: {day}", "UTC-dag: {day}", "UTC日付: {day}", "UTC 日期：{day}", "יום UTC: {day}"],
    [UI_LABELS_FR.emailQuota.loading, "Loading quota…", "Cargando cuota…", "한도 불러오는 중…", "Đang tải hạn mức…", "Laster kvote…", "送信枠を読み込み中…", "正在加载配额…", "טוען מכסה…"],
    [UI_LABELS_FR.emailQuota.warning, "Approaching the limit", "Se aproxima el límite", "한도에 가까워지고 있습니다", "Sắp đạt giới hạn", "Nærmer seg grensen", "上限に近づいています", "即将达到上限", "מתקרבים למגבלה"],
    [UI_LABELS_FR.emailQuota.exhausted, "Quota reached — sending blocked", "Cuota alcanzada — envío bloqueado", "한도 도달 — 전송 차단", "Đã đạt hạn mức — chặn gửi email", "Kvote nådd — sending blokkert", "送信枠の上限に到達 — 送信を停止", "配额已满 — 发送已阻止", "המכסה נוצלה — השליחה חסומה"],
    [UI_LABELS_FR.emailQuota.unavailable, "Quota unavailable — check the service", "Cuota no disponible — compruebe el servicio", "한도를 확인할 수 없음 — 서비스 확인", "Không thể kiểm tra hạn mức — hãy kiểm tra dịch vụ", "Kvote utilgjengelig — kontroller tjenesten", "送信枠を確認できません — サービスを確認", "配额不可用 — 请检查服务", "המכסה אינה זמינה — יש לבדוק את השירות"],
    [UI_LABELS_FR.emailQuota.normal, "Capacity available", "Capacidad disponible", "사용 가능한 용량", "Còn hạn mức sử dụng", "Kapasitet tilgjengelig", "送信可能", "可用额度充足", "נותרה קיבולת"],
    [UI_LABELS_FR.auth.passwordResetRequired.title, "Password reset required", "Debe restablecer la contraseña", "비밀번호 재설정 필요", "Cần đặt lại mật khẩu", "Passordet må tilbakestilles", "パスワードの再設定が必要です", "需要重置密码", "נדרש איפוס סיסמה"],
    [UI_LABELS_FR.auth.passwordResetRequired.required, "Access to protected areas remains blocked until your password has been reset.", "El acceso a las áreas protegidas seguirá bloqueado hasta que se restablezca la contraseña.", "비밀번호를 재설정할 때까지 보호된 영역에 접근할 수 없습니다.", "Quyền truy cập các khu vực được bảo vệ vẫn bị chặn cho đến khi mật khẩu được đặt lại.", "Tilgangen til beskyttede områder er blokkert til passordet er tilbakestilt.", "パスワードを再設定するまで、保護された領域へのアクセスはブロックされます。", "在重置密码之前，受保护区域的访问将保持阻止状态。", "הגישה לאזורים מוגנים נשארת חסומה עד לאיפוס הסיסמה."],
    [UI_LABELS_FR.auth.passwordResetRequired.contact, "Contact a SUPERADMIN to reset your password, or use the password recovery process when available.", "Contacte con un SUPERADMIN para restablecer su contraseña o utilice el proceso de recuperación cuando esté disponible.", "SUPERADMIN에게 비밀번호 재설정을 요청하거나 사용 가능한 경우 비밀번호 복구 절차를 이용하세요.", "Liên hệ SUPERADMIN để đặt lại mật khẩu hoặc sử dụng quy trình khôi phục khi có sẵn.", "Kontakt en SUPERADMIN for å tilbakestille passordet, eller bruk gjenoppretting når den er tilgjengelig.", "SUPERADMINにパスワードの再設定を依頼するか、利用可能な場合はパスワード復旧手順を使用してください。", "请联系 SUPERADMIN 重置密码，或在可用时使用密码恢复流程。", "יש לפנות ל-SUPERADMIN לאיפוס הסיסמה, או להשתמש בתהליך שחזור הסיסמה כאשר הוא זמין."],
    [UI_LABELS_FR.auth.passwordResetRequired.accountPrefix, "Account:", "Cuenta:", "계정:", "Tài khoản:", "Konto:", "対象アカウント:", "账户：", "חשבון:"],
    [UI_LABELS_FR.auth.passwordResetRequired.logout, "Sign out", "Cerrar sesión", "로그아웃", "Đăng xuất", "Logg ut", "ログアウト", "退出登录", "התנתקות"],
    [UI_LABELS_FR.auth.changePasswordRequired.title, "Choose a new password", "Elija una nueva contraseña", "새 비밀번호 선택", "Chọn mật khẩu mới", "Velg et nytt passord", "新しいパスワードを設定", "选择新密码", "בחירת סיסמה חדשה"],
    [UI_LABELS_FR.auth.changePasswordRequired.description, "This account was assigned a temporary password. Set a strong new password to restore normal access.", "Se ha asignado una contraseña temporal a esta cuenta. Defina una nueva contraseña segura para recuperar el acceso normal.", "이 계정에 임시 비밀번호가 지정되었습니다. 정상적인 접근을 위해 새롭고 안전한 비밀번호를 설정하세요.", "Tài khoản này được cấp mật khẩu tạm thời. Hãy đặt mật khẩu mới mạnh để khôi phục quyền truy cập bình thường.", "Kontoen har fått et midlertidig passord. Angi et nytt, sterkt passord for å gjenopprette normal tilgang.", "このアカウントには仮パスワードが設定されています。通常のアクセスを再開するには、強力な新しいパスワードを設定してください。", "此账户已分配临时密码。请设置安全的新密码以恢复正常访问。", "לחשבון הוקצתה סיסמה זמנית. יש להגדיר סיסמה חדשה וחזקה כדי להחזיר את הגישה הרגילה."],
    [UI_LABELS_FR.auth.changePasswordRequired.helper, "Choose a password only you know. Protected areas remain blocked until this step is complete.", "Elija una contraseña que solo usted conozca. Las áreas protegidas seguirán bloqueadas hasta completar este paso.", "본인만 아는 비밀번호를 선택하세요. 이 단계를 완료할 때까지 보호된 영역에 접근할 수 없습니다.", "Chọn mật khẩu chỉ bạn biết. Các khu vực được bảo vệ vẫn bị chặn cho đến khi hoàn tất bước này.", "Velg et passord bare du kjenner. Beskyttede områder er blokkert til dette trinnet er fullført.", "自分だけが知っているパスワードを設定してください。この手順が完了するまで保護された領域にはアクセスできません。", "请选择只有您知道的密码。在完成此步骤之前，受保护区域将保持阻止状态。", "יש לבחור סיסמה שרק אתם יודעים. האזורים המוגנים נשארים חסומים עד להשלמת שלב זה."],
    [UI_LABELS_FR.auth.changePasswordRequired.submit, "Save new password", "Guardar nueva contraseña", "새 비밀번호 저장", "Lưu mật khẩu mới", "Lagre nytt passord", "新しいパスワードを保存", "保存新密码", "שמירת הסיסמה החדשה"],
    [UI_LABELS_FR.auth.changePasswordRequired.mismatch, "Both passwords must match.", "Las dos contraseñas deben coincidir.", "두 비밀번호가 일치해야 합니다.", "Hai mật khẩu phải giống nhau.", "Begge passordene må være like.", "2つのパスワードは一致している必要があります。", "两次输入的密码必须一致。", "שתי הסיסמאות חייבות להיות זהות."],
    [UI_LABELS_FR.auth.changePasswordRequired.success, "New password saved. Sign in again with your new password.", "Nueva contraseña guardada. Inicie sesión de nuevo con ella.", "새 비밀번호가 저장되었습니다. 새 비밀번호로 다시 로그인하세요.", "Đã lưu mật khẩu mới. Hãy đăng nhập lại bằng mật khẩu mới.", "Nytt passord er lagret. Logg inn igjen med det nye passordet.", "新しいパスワードを保存しました。新しいパスワードで再度ログインしてください。", "新密码已保存。请使用新密码重新登录。", "הסיסמה החדשה נשמרה. יש להתחבר שוב עם הסיסמה החדשה."],
];

const languages = ["fr", "en", "es", "ko", "vi", "no", "ja", "zh", "he"];
export function localizeCoreUiLabel(source: string, locale: string): string | null {
    const row = coreUiRows.find(entry => entry[0] === source);
    return row?.[languages.indexOf(baseUiLocale(locale))] ?? null;
}
