import { UI_LABELS_FR } from "./uiLabels.fr";
type Labels = { [K in keyof typeof UI_LABELS_FR.receptionReplan]: string };
export const receptionReplanTranslations: Record<string, Labels> = {
    fr: UI_LABELS_FR.receptionReplan,
    en: { notice: "An appointment is already scheduled at this clinic: {date} at {time}.", start: "Reschedule this appointment", confirm: "Confirm appointment replacement", kept: "The original appointment stays reserved until the new time is confirmed. If booking fails, it is kept.", conflict: "The appointment changed or several appointments are scheduled. Search for the patient again. Existing duplicates must be reviewed before continuing.", success: "Appointment rescheduled. The previous appointment remains in the history." },
    es: { notice: "Ya hay una cita programada en esta clínica: {date} a las {time}.", start: "Reprogramar esta cita", confirm: "Confirmar el reemplazo de la cita", kept: "La cita original se conserva hasta confirmar el nuevo horario. Si la reserva falla, se mantiene.", conflict: "La cita cambió o hay varias citas programadas. Busque al paciente de nuevo. Los duplicados existentes deben revisarse antes de continuar.", success: "Cita reprogramada. La cita anterior permanece en el historial." },
    ko: { notice: "이 클리닉에 이미 예약이 있습니다: {date} {time}.", start: "이 예약 변경", confirm: "예약 교체 확인", kept: "새 시간이 확정될 때까지 기존 예약이 유지됩니다. 예약에 실패해도 기존 예약은 유지됩니다.", conflict: "예약이 변경되었거나 여러 예약이 있습니다. 환자를 다시 검색하세요. 계속하기 전에 기존 중복 예약을 검토해야 합니다.", success: "예약이 변경되었습니다. 이전 예약은 기록에 남습니다." },
    vi: { notice: "Đã có lịch hẹn tại phòng khám này: {date} lúc {time}.", start: "Đổi lịch hẹn này", confirm: "Xác nhận thay thế lịch hẹn", kept: "Lịch hẹn ban đầu được giữ cho đến khi xác nhận giờ mới. Nếu đặt lịch thất bại, lịch cũ vẫn được giữ.", conflict: "Lịch hẹn đã thay đổi hoặc có nhiều lịch hẹn. Hãy tìm lại bệnh nhân. Cần xem xét các lịch trùng trước khi tiếp tục.", success: "Đã đổi lịch hẹn. Lịch hẹn trước vẫn được lưu trong lịch sử." },
    no: { notice: "En time er allerede bestilt ved denne klinikken: {date} kl. {time}.", start: "Flytt denne timen", confirm: "Bekreft erstatning av timen", kept: "Den opprinnelige timen beholdes til det nye tidspunktet er bekreftet. Hvis bestillingen mislykkes, beholdes den.", conflict: "Timen er endret eller flere timer er bestilt. Søk etter pasienten på nytt. Eksisterende duplikater må gjennomgås før du fortsetter.", success: "Timen er flyttet. Den forrige timen beholdes i historikken." },
    ja: { notice: "このクリニックには既に予約があります：{date} {time}。", start: "この予約を変更", confirm: "予約の変更を確定", kept: "新しい時間が確定するまで元の予約は維持されます。予約に失敗した場合も維持されます。", conflict: "予約が変更されたか、複数の予約があります。患者を再検索してください。続行する前に既存の重複予約を確認する必要があります。", success: "予約を変更しました。以前の予約は履歴に残ります。" },
    zh: { notice: "此诊所已有预约：{date} {time}。", start: "重新安排此预约", confirm: "确认替换预约", kept: "在新时间确认前，原预约将保留。若预约失败，原预约不变。", conflict: "预约已变更或已有多个预约。请重新搜索患者。继续前须核查现有重复预约。", success: "预约已重新安排。原预约将保留在历史记录中。" },
    he: { notice: "כבר נקבע תור במרפאה זו: {date} בשעה {time}.", start: "שינוי מועד התור", confirm: "אישור החלפת התור", kept: "התור המקורי נשמר עד לאישור המועד החדש. אם ההזמנה נכשלת, התור המקורי נשאר.", conflict: "התור השתנה או שקיימים כמה תורים. חפשו את המטופל מחדש. יש לבדוק כפילויות קיימות לפני שממשיכים.", success: "מועד התור שונה. התור הקודם נשמר בהיסטוריה." },
};
export const receptionReplanLabels = (locale: string): Labels => receptionReplanTranslations[locale.split("-")[0]] || receptionReplanTranslations.en;
