import { UI_LABELS_FR } from "./uiLabels.fr";
// Medical safety content: versioned French source, fixed English rendering.
export const walkInEmergencyReminder = {
    kind: "medical",
    sourceFr: UI_LABELS_FR.walkInEmergencyReminder,
    text: "If the patient appears seriously unwell, reception staff must strongly recommend going to an emergency department, following the clinic's protocol. Returning tomorrow or booking a later appointment must not delay urgent care.",
} as const;
type Labels = { [K in keyof typeof UI_LABELS_FR.urgentologist]: string };
export const urgentologistTranslations: Record<string, Labels> = {
    fr: UI_LABELS_FR.urgentologist,
    en: { unavailableToday: "No emergency physician appointment is available today at this clinic.", dailyLimitReached: "The daily appointment limit has been reached for this physician. Refresh the available appointments.", hint: "Walk-in only. The daily limit includes scheduled or completed consultations across all clinics. Remove regular slots before changing the specialty.", full: "All emergency physicians at this clinic have reached their limit of {limit} consultations for today.", tomorrow: "Return tomorrow", family: "View family physician appointments", tomorrowNotice: "No booking has been created. Returning tomorrow does not guarantee a place. This administrative option does not assess medical urgency." },
    es: { unavailableToday: "No hay citas con médicos de urgencias disponibles hoy en esta clínica.", dailyLimitReached: "Se ha alcanzado el límite diario de citas de este médico. Actualice las citas disponibles.", hint: "Solo sin cita previa. El límite diario incluye las consultas programadas o realizadas en todas las clínicas. Retire los horarios regulares antes de cambiar la especialidad.", full: "Todos los médicos de urgencias de esta clínica han alcanzado su límite de {limit} consultas para hoy.", tomorrow: "Volver mañana", family: "Ver citas de médicos de familia", tomorrowNotice: "No se ha creado ninguna reserva. Volver mañana no garantiza una plaza. Esta opción administrativa no evalúa la urgencia médica." },
    ko: { unavailableToday: "오늘 이 클리닉에는 응급의학 의사의 예약 가능한 시간이 없습니다.", dailyLimitReached: "이 의사의 일일 예약 한도에 도달했습니다. 가능한 예약을 새로고침하세요.", hint: "워크인 전용. 일일 한도에는 모든 클리닉의 예약 또는 완료된 진료가 포함됩니다. 전문 분야 변경 전 일반 시간대를 제거하세요.", full: "이 클리닉의 모든 응급의학 의사가 오늘 진료 한도인 {limit}건에 도달했습니다.", tomorrow: "내일 다시 방문", family: "가정의학과 예약 보기", tomorrowNotice: "예약이 생성되지 않았습니다. 내일 방문해도 자리가 보장되지 않습니다. 이 행정 옵션은 의학적 긴급성을 평가하지 않습니다." },
    vi: { unavailableToday: "Hôm nay không có lịch hẹn bác sĩ cấp cứu còn trống tại phòng khám này.", dailyLimitReached: "Đã đạt giới hạn lịch hẹn hằng ngày của bác sĩ này. Hãy tải lại các lịch hẹn còn trống.", hint: "Chỉ tiếp nhận walk-in. Giới hạn hằng ngày bao gồm các lượt khám đã đặt hoặc hoàn tất tại mọi phòng khám. Xóa các khung giờ thường trước khi đổi chuyên khoa.", full: "Tất cả bác sĩ cấp cứu tại phòng khám này đã đạt giới hạn {limit} lượt khám hôm nay.", tomorrow: "Quay lại ngày mai", family: "Xem lịch bác sĩ gia đình", tomorrowNotice: "Chưa tạo lịch hẹn nào. Quay lại ngày mai không đảm bảo có chỗ. Lựa chọn hành chính này không đánh giá mức độ khẩn cấp y tế." },
    no: { unavailableToday: "Ingen timer hos akuttlege er tilgjengelige ved denne klinikken i dag.", dailyLimitReached: "Den daglige timegrensen for denne legen er nådd. Oppdater tilgjengelige timer.", hint: "Kun drop-in. Dagsgrensen omfatter bestilte eller fullførte konsultasjoner på tvers av klinikker. Fjern ordinære timer før du endrer spesialitet.", full: "Alle akuttlegene ved denne klinikken har nådd grensen på {limit} konsultasjoner i dag.", tomorrow: "Kom tilbake i morgen", family: "Se timer hos allmennleger", tomorrowNotice: "Ingen time er bestilt. Å komme tilbake i morgen garanterer ikke plass. Dette administrative valget vurderer ikke medisinsk hastegrad." },
    ja: { unavailableToday: "本日、このクリニックには救急医の空き予約枠がありません。", dailyLimitReached: "この医師の1日の予約上限に達しました。空き予約を更新してください。", hint: "ウォークイン専用。1日の上限には全クリニックの予約済み・診察済みの診療が含まれます。専門分野を変更する前に通常枠を削除してください。", full: "このクリニックのすべての救急医が本日の上限{limit}件に達しました。", tomorrow: "明日再来院する", family: "家庭医の予約枠を見る", tomorrowNotice: "予約は作成されていません。明日の来院で空きが保証されるわけではありません。この事務上の選択肢は医学的緊急性を判断しません。" },
    zh: { unavailableToday: "今天此诊所没有急诊医生的可用预约时段。", dailyLimitReached: "此医生已达到每日预约上限。请刷新可用预约。", hint: "仅限随到随诊。每日上限包括所有诊所的已预约或已完成诊疗。更改专科前请移除常规时段。", full: "此诊所所有急诊医生均已达到今天{limit}次诊疗的上限。", tomorrow: "明天再来", family: "查看家庭医生预约", tomorrowNotice: "未创建任何预约。明天再来并不保证有名额。此行政选项不评估医疗紧急程度。" },
    he: { unavailableToday: "אין היום תורים זמינים לרופאי רפואה דחופה במרפאה זו.", dailyLimitReached: "הושגה מכסת התורים היומית של רופא זה. יש לרענן את התורים הזמינים.", hint: "קבלה ללא תור קבוע בלבד. המכסה היומית כוללת מפגשים מוזמנים או שהושלמו בכל המרפאות. יש להסיר שעות רגילות לפני שינוי ההתמחות.", full: "כל רופאי הרפואה הדחופה במרפאה הגיעו היום למכסה של {limit} מפגשים.", tomorrow: "לחזור מחר", family: "הצגת תורים לרופאי משפחה", tomorrowNotice: "לא נוצרה הזמנה. חזרה מחר אינה מבטיחה מקום. אפשרות מנהלית זו אינה מעריכה דחיפות רפואית." },
};
export const urgentologistLabels = (locale: string, limit = 20): Labels => {
    const labels = urgentologistTranslations[locale.split("-")[0]] || urgentologistTranslations.en;
    return { ...labels, full: labels.full.replace("{limit}", String(limit)) };
};
