import { UI_LABELS_FR } from "./uiLabels.fr";
const fr = UI_LABELS_FR.validationReports;
type Labels = { [K in keyof typeof fr]: string };
const translated: Record<string, string[]> = {
    en: ["Validation reports", "Refresh", "Backend image commit", "Unknown version — correspondence cannot be verified", "No reports published.", "Unable to load or download the report.", "Tested commit matches the deployed image", "Deployed version not covered by this report", "Uncommitted changes — the commit alone does not describe the tested version", "Tests passed", "Failed or incomplete validation", "Download PDF", "Download evidence (JSON)", "Isolated validation, not a test of this Coolify deployment or a security certification. Hashes detect changes but do not authenticate the author.", "Invalid report files were excluded.", "Loading…", "Run", "Tested commit", "Validation finished", "Cleanup confirmed", "Yes", "No", "Same slot", "Same patient", "Last emergency physician place", "Concurrent cancellation and rescheduling", "API authorization", "Atomicity and minimized audits", "Runs", "Concurrency tests", "Walk-in appointment booking", "Latest validation"],
    es: ["Informes de validación", "Actualizar", "Commit de la imagen backend", "Versión desconocida — no se puede verificar la correspondencia", "No hay informes publicados.", "No se puede cargar o descargar el informe.", "El commit probado coincide con la imagen desplegada", "La versión desplegada no está cubierta por este informe", "Cambios sin commit — el commit no describe por sí solo la versión probada", "Pruebas superadas", "Validación fallida o incompleta", "Descargar PDF", "Descargar evidencias (JSON)", "Validación aislada, no una prueba de este despliegue Coolify ni una certificación de seguridad. Las huellas detectan cambios, pero no autentican al autor.", "Se excluyeron archivos de informe no válidos.", "Cargando…", "Ejecución", "Commit probado", "Fin de validación", "Limpieza confirmada", "Sí", "No", "Mismo horario", "Mismo paciente", "Última plaza de urgencias", "Cancelación y reprogramación concurrentes", "Autorización API", "Atomicidad y auditorías minimizadas", "Ejecuciones", "Pruebas de concurrencia", "Reserva de citas sin cita previa", "Última validación"],
    ko: ["검증 보고서", "새로고침", "백엔드 이미지 커밋", "버전 알 수 없음 — 일치 여부 확인 불가", "게시된 보고서가 없습니다.", "보고서를 불러오거나 다운로드할 수 없습니다.", "테스트한 커밋이 배포된 이미지와 일치합니다", "이 보고서는 배포된 버전을 검증하지 않습니다", "커밋되지 않은 변경 — 커밋만으로 테스트 버전을 설명할 수 없습니다", "테스트 통과", "검증 실패 또는 불완전", "PDF 다운로드", "증거 다운로드 (JSON)", "격리된 검증이며 이 Coolify 배포 테스트나 보안 인증이 아닙니다. 해시는 변경을 감지하지만 작성자를 인증하지 않습니다.", "유효하지 않은 보고서 파일이 제외되었습니다.", "로딩 중…", "실행", "테스트 커밋", "검증 완료 시각", "정리 확인", "예", "아니요", "동일 시간대", "동일 환자", "응급의 마지막 진료 자리", "동시 취소 및 일정 변경", "API 권한", "원자성 및 최소화된 감사", "실행 횟수", "동시성 테스트", "당일 방문 진료 예약", "최근 검증"],
    vi: ["Báo cáo kiểm thử", "Làm mới", "Commit ảnh backend", "Không rõ phiên bản — không thể xác minh sự khớp", "Chưa có báo cáo.", "Không thể tải báo cáo.", "Commit kiểm thử khớp với ảnh đã triển khai", "Báo cáo không bao phủ phiên bản đã triển khai", "Thay đổi chưa commit — commit không mô tả đầy đủ phiên bản đã kiểm thử", "Kiểm thử đạt", "Kiểm thử thất bại hoặc chưa đầy đủ", "Tải PDF", "Tải bằng chứng (JSON)", "Kiểm thử cô lập, không phải kiểm thử triển khai Coolify này hay chứng nhận bảo mật. Mã băm phát hiện thay đổi nhưng không xác thực tác giả.", "Đã loại các tệp báo cáo không hợp lệ.", "Đang tải…", "Lần chạy", "Commit kiểm thử", "Kết thúc kiểm thử", "Đã xác nhận dọn dẹp", "Có", "Không", "Cùng khung giờ", "Cùng bệnh nhân", "Suất khám cấp cứu cuối cùng", "Hủy và đổi lịch đồng thời", "Phân quyền API", "Tính nguyên tử và nhật ký tối thiểu", "Lần chạy", "Kiểm thử đồng thời", "Đặt lịch khám không hẹn trước", "Lần kiểm thử gần nhất"],
    no: ["Valideringsrapporter", "Oppdater", "Backend-imagens commit", "Ukjent versjon — samsvar kan ikke bekreftes", "Ingen publiserte rapporter.", "Rapporten kunne ikke lastes ned.", "Testet commit samsvarer med distribuert image", "Distribuert versjon dekkes ikke av rapporten", "Endringer uten commit — commit alene beskriver ikke testet versjon", "Tester bestått", "Mislykket eller ufullstendig validering", "Last ned PDF", "Last ned bevis (JSON)", "Isolert validering, ikke en test av denne Coolify-distribusjonen eller en sikkerhetssertifisering. Hashverdier oppdager endringer, men autentiserer ikke forfatteren.", "Ugyldige rapportfiler ble utelatt.", "Laster…", "Kjøring", "Testet commit", "Validering avsluttet", "Opprydding bekreftet", "Ja", "Nei", "Samme tidspunkt", "Samme pasient", "Siste plass hos akuttlege", "Samtidig avbestilling og ombooking", "API-tilgang", "Atomisitet og minimerte revisjonslogger", "Kjøringer", "Samtidighetstester", "Bestilling av drop-in-time", "Siste validering"],
    ja: ["検証レポート", "更新", "バックエンドイメージのコミット", "バージョン不明 — 一致を確認できません", "公開されたレポートはありません。", "レポートを読み込みまたはダウンロードできません。", "テストしたコミットは配備イメージと一致します", "このレポートは配備バージョンを対象としていません", "未コミットの変更 — コミットだけではテストバージョンを特定できません", "テスト合格", "検証失敗または未完了", "PDFをダウンロード", "証拠をダウンロード (JSON)", "隔離された検証であり、このCoolify配備のテストやセキュリティ認証ではありません。ハッシュは変更を検出しますが作成者を認証しません。", "無効なレポートファイルは除外されました。", "読み込み中…", "実行", "テストしたコミット", "検証終了", "クリーンアップ確認", "はい", "いいえ", "同一時間枠", "同一患者", "救急医の最後の枠", "同時キャンセルと予約変更", "API権限", "原子性と最小化した監査ログ", "実行回数", "並行性テスト", "予約なし来院の診療予約", "最新の検証"],
    zh: ["验证报告", "刷新", "后端镜像提交", "版本未知 — 无法验证是否匹配", "尚未发布报告。", "无法加载或下载报告。", "测试提交与部署镜像匹配", "此报告不涵盖已部署版本", "存在未提交的更改 — 仅凭提交无法描述测试版本", "测试通过", "验证失败或不完整", "下载 PDF", "下载证据 (JSON)", "这是隔离验证，不是对此 Coolify 部署的测试或安全认证。哈希可检测更改，但不能认证作者。", "已排除无效报告文件。", "加载中…", "运行", "测试提交", "验证结束", "已确认清理", "是", "否", "同一时间段", "同一患者", "急诊医生最后一个名额", "并发取消和改期", "API 授权", "原子性及最小化审计", "运行次数", "并发测试", "无预约患者挂号", "最近验证"],
    he: ["דוחות אימות", "רענון", "Commit של תמונת השרת", "גרסה לא ידועה — אי אפשר לאמת התאמה", "לא פורסמו דוחות.", "לא ניתן לטעון או להוריד את הדוח.", "הקומיט שנבדק תואם לתמונה שנפרסה", "הגרסה שנפרסה אינה מכוסה בדוח זה", "שינויים ללא commit — הקומיט לבדו אינו מתאר את הגרסה שנבדקה", "הבדיקות עברו", "האימות נכשל או אינו שלם", "הורדת PDF", "הורדת ראיות (JSON)", "אימות מבודד, לא בדיקה של פריסת Coolify זו ולא הסמכת אבטחה. גיבובים מזהים שינויים אך אינם מאמתים את המחבר.", "קובצי דוח לא תקינים הוחרגו.", "טוען…", "הרצה", "הקומיט שנבדק", "סיום האימות", "הניקוי אושר", "כן", "לא", "אותו מועד", "אותו מטופל", "המקום האחרון לרופא חירום", "ביטול ושינוי מועד במקביל", "הרשאות API", "אטומיות ורישומי ביקורת מצומצמים", "הרצות", "בדיקות מקביליות", "קביעת תור למגיעים ללא תיאום מראש", "האימות האחרון"],
};
export const validationReportLabels = (locale: string): Labels => {
    const lang = locale.split("-")[0];
    if (lang === "fr") return fr;
    const values = translated[lang] || translated.en;
    return Object.fromEntries(Object.keys(fr).map((key, i) => [key, values[i]])) as Labels;
};
